'use strict';
angular.module('myApp.main.landingPage', ['ui.router', 'ngMap'])

.config(function ($stateProvider) {
  $stateProvider
    .state('myApp.main.landingPage', {
      url: '/landingPage',
      templateUrl: 'landingPage/landingPage.tpl.html',
      controller: 'SearchController'
    });
})

.controller('SearchController', function($scope, DataRequestFactory, $rootElement, $location, $q, $state){
  
  $scope.search = function(){
    console.log("search function is firing")
    var fullInput = $scope.result;
    var firstFiveCharactersOfInput = fullInput.slice(0,5);
    if(isNaN(firstFiveCharactersOfInput)){
      console.log("candidate: ", fullInput)
      $state.go('myApp.main.candidateProfile',{input: fullInput });
    }else if(!isNaN(firstFiveCharactersOfInput)){
      console.log("zip: ", firstFiveCharactersOfInput);
      $state.go('myApp.main.candidateList',{input: firstFiveCharactersOfInput });
    }else{
      $scope.message = "No results found";
      }
    }

  $scope.$on('mapInitialized', function(event, map) {
    var layerDistricts = new google.maps.FusionTablesLayer({
      query: {
        select: 'col0',
        from: '1BAwVHJLmofCdgz3ewBHN_42SHqjK7VV3sfek26Fm'
      },
      styles: [{
        polygonOptions: {
          fillColor: '#F0F0F0',
          fillOpacity: 0.5
        }
      }]      
    });
    var layerKochRecipients = new google.maps.FusionTablesLayer({
      query: {
        select: 'col6',
        from: '1yD-ZmXy4Lgo4DC9-HmvwxYcvcYfIDzZdNpJEKvtx'
      }
    });

    layerDistricts.setMap(map);
    layerKochRecipients.setMap(map);
    });

  $scope.message = 'Search for a zip code / candidate';
  
  //this function gets the current location of the user and saves it as $scope.position
  // $scope.getLocation = function(){
  //   $window.navigator.geolocation.getCurrentPosition(function(position, error){
  //     console.dir(position);   
  //       $scope.position = position;
  //       // $scope.findDistrictByLongLat();
  //       if(error){ console.log(error)};
  //     }
  //  )}();


  $scope.people = ['John','Kevin', 'Liam'];

$scope.candidates = [{voteSmartId:146132,firstName:"David",lastName:"Cox",info:"U.S. House (R) - FL"},
{voteSmartId:140387,firstName:"Jim",lastName:"Mcdermott",info:"U.S. House (D) - AK"},
{voteSmartId:146066,firstName:"John",lastName:"Lewis",info:"U.S. House (D) - MT"},
{voteSmartId:153494,firstName:"Mark",lastName:"Harris",info:"U.S. House (R) - WI"},
{voteSmartId:150213,firstName:"Matt",lastName:"Moore",info:"U.S. House (D) - MS"},
{voteSmartId:153217,firstName:"Paul",lastName:"Cook",info:"U.S. House (R) - TN"},
{voteSmartId:155061,firstName:"Sam",lastName:"Johnson",info:"U.S. House (R) - MI"},
{voteSmartId:8168,firstName:"Susan",lastName:"Davis",info:"U.S. House (R) - CA"},
{voteSmartId:246,firstName:"John M",lastName:"Shimkus",info:"U.S. House (R) - IL"},
{voteSmartId:265,firstName:"Joe",lastName:"Pitts",info:"U.S. House (R) - PA"},
{voteSmartId:288,firstName:"Pete",lastName:"Sessions",info:"U.S. House (R) - TX"},
{voteSmartId:441,firstName:"Robert B",lastName:"Aderholt",info:"U.S. House (R) - AL"},
{voteSmartId:444,firstName:"Kevin",lastName:"Cramer",info:"U.S. House (R) - ND"},
{voteSmartId:1535,firstName:"Mike",lastName:"Coffman",info:"U.S. House (R) - CO"},
{voteSmartId:2062,firstName:"Candice S",lastName:"Miller",info:"U.S. House (R) - MI"},
{voteSmartId:2698,firstName:"Douglas L",lastName:"Lamborn",info:"U.S. House (R) - CO"},
{voteSmartId:2917,firstName:"Mike",lastName:"Simpson",info:"U.S. House (R) - ID"},
{voteSmartId:2979,firstName:"Greg",lastName:"Walden",info:"U.S. House (R) - OR"},
{voteSmartId:3217,firstName:"Rodgers, Cathy",lastName:"Mcmorris Rodgers",info:"U.S. House (R) - WA"},
{voteSmartId:3833,firstName:"Erik",lastName:"Paulsen",info:"U.S. House (R) - MN"},
{voteSmartId:4430,firstName:"Scott",lastName:"Garrett",info:"U.S. House (R) - NJ"},
{voteSmartId:5148,firstName:"Morgan",lastName:"Griffith",info:"U.S. House (R) - VA"},
{voteSmartId:5488,firstName:"John",lastName:"Culberson",info:"U.S. House (R) - TX"},
{voteSmartId:5549,firstName:"Kenny",lastName:"Marchant",info:"U.S. House (R) - TX"},
{voteSmartId:6051,firstName:"Virginia",lastName:"Foxx",info:"U.S. House (R) - NC"},
{voteSmartId:6302,firstName:"Mike",lastName:"Bost",info:"U.S. House (R) - IL"},
{voteSmartId:6382,firstName:"Peter",lastName:"Roskam",info:"U.S. House (R) - IL"},
{voteSmartId:8158,firstName:"Jim",lastName:"Jordan",info:"U.S. House (R) - OH"},
{voteSmartId:8297,firstName:"Evan",lastName:"Jenkins",info:"U.S. House (R) - WV"},
{voteSmartId:8326,firstName:"Alan",lastName:"Nunnelee",info:"U.S. House (R) - MS"},
{voteSmartId:8404,firstName:"Patrick J",lastName:"Tiberi",info:"U.S. House (R) - OH"},
{voteSmartId:8618,firstName:"Tim",lastName:"Walberg",info:"U.S. House (R) - MI"},
{voteSmartId:8783,firstName:"Vicky",lastName:"Hartzler",info:"U.S. House (R) - MO"},
{voteSmartId:9026,firstName:"Steve",lastName:"Scalise",info:"U.S. House (R) - LA"},
{voteSmartId:9121,firstName:"Charlie",lastName:"Dent",info:"U.S. House (R) - PA"},
{voteSmartId:9622,firstName:"Rodney",lastName:"Davis",info:"U.S. House (R) - IL"},
{voteSmartId:9715,firstName:"Tom",lastName:"Mcclintock",info:"U.S. House (R) - CA"},
{voteSmartId:9794,firstName:"Tim",lastName:"Murphy",info:"U.S. House (R) - PA"},
{voteSmartId:9926,firstName:"Robert E",lastName:"Latta",info:"U.S. House (R) - OH"},
{voteSmartId:10655,firstName:"Steve",lastName:"Pearce",info:"U.S. House (R) - NM"},
{voteSmartId:10853,firstName:"Steven A",lastName:"King",info:"U.S. House (R) - IA"},
{voteSmartId:11812,firstName:"Austin",lastName:"Scott",info:"U.S. House (R) - GA"},
{voteSmartId:11853,firstName:"Tom",lastName:"Price",info:"U.S. House (R) - GA"},
{voteSmartId:12571,firstName:"Tim",lastName:"Huelskamp",info:"U.S. House (R) - KS"},
{voteSmartId:12813,firstName:"Dennis",lastName:"Ross",info:"U.S. House (R) - FL"},
{voteSmartId:15546,firstName:"Cynthia Marie",lastName:"Lummis",info:"U.S. House (R) - WY"},
{voteSmartId:16553,firstName:"Darrell",lastName:"Issa",info:"U.S. House (R) - CA"},
{voteSmartId:16725,firstName:"Devin",lastName:"Nunes",info:"U.S. House (R) - CA"},
{voteSmartId:16765,firstName:"Tony",lastName:"Strickland",info:"U.S. House (R) - CA"},
{voteSmartId:17188,firstName:"John B",lastName:"Larson",info:"U.S. House (D) - CT"},
{voteSmartId:18199,firstName:"Randy",lastName:"Hultgren",info:"U.S. House (R) - IL"},
{voteSmartId:18594,firstName:"Lynn",lastName:"Jenkins",info:"U.S. House (R) - KS"},
{voteSmartId:18829,firstName:"Brett",lastName:"Guthrie",info:"U.S. House (R) - KY"},
{voteSmartId:20311,firstName:"John",lastName:"Kline",info:"U.S. House (R) - MN"},
{voteSmartId:20400,firstName:"Blaine",lastName:"Luetkemeyer",info:"U.S. House (R) - MO"},
{voteSmartId:21031,firstName:"Patrick",lastName:"Mchenry",info:"U.S. House (R) - NC"},
{voteSmartId:21276,firstName:"Lee",lastName:"Terry",info:"U.S. House (R) - NE"},
{voteSmartId:21284,firstName:"Adrian",lastName:"Smith",info:"U.S. House (R) - NE"},
{voteSmartId:21873,firstName:"Ed",lastName:"Whitfield",info:"U.S. House (R) - KY"},
{voteSmartId:21991,firstName:"Mark",lastName:"Sanford",info:"U.S. House (R) - SC"},
{voteSmartId:22177,firstName:"Rodney",lastName:"Frelinghuysen",info:"U.S. House (R) - NJ"},
{voteSmartId:22184,firstName:"Matt",lastName:"Salmon",info:"U.S. House (R) - AZ"},
{voteSmartId:24046,firstName:"Glenn",lastName:"Thompson",info:"U.S. House (R) - PA"},
{voteSmartId:25186,firstName:"Marsha",lastName:"Blackburn",info:"U.S. House (R) - TN"},
{voteSmartId:25292,firstName:"Diane",lastName:"Black",info:"U.S. House (R) - TN"},
{voteSmartId:26344,firstName:"Paul",lastName:"Ryan",info:"U.S. House (R) - WI"},
{voteSmartId:26772,firstName:"Ed",lastName:"Royce",info:"U.S. House (R) - CA"},
{voteSmartId:26817,firstName:"Sanford",lastName:"Bishop",info:"U.S. House (D) - GA"},
{voteSmartId:26906,firstName:"Fred",lastName:"Upton",info:"U.S. House (R) - MI"},
{voteSmartId:26926,firstName:"Collin",lastName:"Peterson",info:"U.S. House (D) - MN"},
{voteSmartId:26952,firstName:"Chris",lastName:"Smith",info:"U.S. House (R) - NJ"},
{voteSmartId:27015,firstName:"John",lastName:"Boehner",info:"U.S. House (R) - OH"},
{voteSmartId:27097,firstName:"Lamar",lastName:"Smith",info:"U.S. House (R) - TX"},
{voteSmartId:27116,firstName:"Bob",lastName:"Goodlatte",info:"U.S. House (R) - VA"},
{voteSmartId:27142,firstName:"F James Jr",lastName:"Sensenbrenner",info:"U.S. House (R) - WI"},
{voteSmartId:28769,firstName:"Jeff",lastName:"Denham",info:"U.S. House (R) - CA"},
{voteSmartId:29051,firstName:"Jeff",lastName:"Gorell",info:"U.S. House (R) - CA"},
{voteSmartId:29346,firstName:"Mimi",lastName:"Walters",info:"U.S. House (R) - CA"},
{voteSmartId:29713,firstName:"Doug",lastName:"Lamalfa",info:"U.S. House (R) - CA"},
{voteSmartId:31618,firstName:"Barry",lastName:"Loudermilk",info:"U.S. House (R) - GA"},
{voteSmartId:31780,firstName:"John",lastName:"Barrow",info:"U.S. House (D) - GA"},
{voteSmartId:31969,firstName:"Tom",lastName:"Graves",info:"U.S. House (R) - GA"},
{voteSmartId:33428,firstName:"Aaron",lastName:"Schock",info:"U.S. House (R) - IL"},
{voteSmartId:34167,firstName:"Todd",lastName:"Rokita",info:"U.S. House (R) - IN"},
{voteSmartId:34205,firstName:"Jackie",lastName:"Walorski",info:"U.S. House (R) - IN"},
{voteSmartId:34230,firstName:"Marlin",lastName:"Stutzman",info:"U.S. House (R) - IN"},
{voteSmartId:34433,firstName:"Kevin",lastName:"Yoder",info:"U.S. House (R) - KS"},
{voteSmartId:35514,firstName:"Charles W Jr",lastName:"Boustany",info:"U.S. House (R) - LA"},
{voteSmartId:38351,firstName:"Bill",lastName:"Huizenga",info:"U.S. House (R) - MI"},
{voteSmartId:41272,firstName:"Robert",lastName:"Pittenger",info:"U.S. House (R) - NC"},
{voteSmartId:42946,firstName:"Frank",lastName:"Guinta",info:"U.S. House (R) - NH"},
{voteSmartId:44082,firstName:"Joe",lastName:"Heck",info:"U.S. House (R) - NV"},
{voteSmartId:45466,firstName:"Bob",lastName:"Gibbs",info:"U.S. House (R) - OH"},
{voteSmartId:46034,firstName:"Tom",lastName:"Cole",info:"U.S. House (R) - OK"},
{voteSmartId:46971,firstName:"Michael G",lastName:"Fitzpatrick",info:"U.S. House (R) - PA"},
{voteSmartId:47143,firstName:"Lou",lastName:"Barletta",info:"U.S. House (R) - PA"},
{voteSmartId:49210,firstName:"Michael",lastName:"Mccaul",info:"U.S. House (R) - TX"},
{voteSmartId:49296,firstName:"John",lastName:"Carter",info:"U.S. House (R) - TX"},
{voteSmartId:49522,firstName:"Randy",lastName:"Neugebauer",info:"U.S. House (R) - TX"},
{voteSmartId:49827,firstName:"Jeb",lastName:"Hensarling",info:"U.S. House (R) - TX"},
{voteSmartId:49935,firstName:"Mike",lastName:"Conaway",info:"U.S. House (R) - TX"},
{voteSmartId:50029,firstName:"Louis B Jr",lastName:"Gohmert",info:"U.S. House (R) - TX"},
{voteSmartId:50112,firstName:"Roger",lastName:"Williams",info:"U.S. House (R) - TX"},
{voteSmartId:50120,firstName:"Michael",lastName:"Burgess",info:"U.S. House (R) - TX"},
{voteSmartId:50895,firstName:"Robert",lastName:"Hurt",info:"U.S. House (R) - VA"},
{voteSmartId:55693,firstName:"Bill",lastName:"Shuster",info:"U.S. House (R) - PA"},
{voteSmartId:57391,firstName:"Raul",lastName:"Labrador",info:"U.S. House (R) - ID"},
{voteSmartId:58189,firstName:"Kristi",lastName:"Noem",info:"U.S. House (R) - SD"},
{voteSmartId:59980,firstName:"Scott",lastName:"Perry",info:"U.S. House (R) - PA"},
{voteSmartId:60348,firstName:"Mick",lastName:"Mulvaney",info:"U.S. House (R) - SC"},
{voteSmartId:65403,firstName:"Scott",lastName:"Tipton",info:"U.S. House (R) - CO"},
{voteSmartId:67851,firstName:"Doug",lastName:"Collins",info:"U.S. House (R) - GA"},
{voteSmartId:68079,firstName:"Andy",lastName:"Tobin",info:"U.S. House (R) - AZ"},
{voteSmartId:69075,firstName:"Marilinda",lastName:"Garcia",info:"U.S. House (R) - NH"},
{voteSmartId:69521,firstName:"Steven",lastName:"Palazzo",info:"U.S. House (R) - MS"},
{voteSmartId:71815,firstName:"Steve",lastName:"Womack",info:"U.S. House (R) - AR"},
{voteSmartId:74052,firstName:"Darlene",lastName:"Senger",info:"U.S. House (R) - IL"},
{voteSmartId:82026,firstName:"Dan",lastName:"Logue",info:"U.S. House (R) - CA"},
{voteSmartId:101907,firstName:"Beutler, Jaime",lastName:"Herrera Beutler",info:"U.S. House (R) - WA"},
{voteSmartId:101985,firstName:"Gregg",lastName:"Harper",info:"U.S. House (R) - MS"},
{voteSmartId:102008,firstName:"Pete",lastName:"Olson",info:"U.S. House (R) - TX"},
{voteSmartId:102026,firstName:"Randy",lastName:"Weber",info:"U.S. House (R) - TX"},
{voteSmartId:102964,firstName:"David",lastName:"Rouzer",info:"U.S. House (R) - NC"},
{voteSmartId:103482,firstName:"Jason",lastName:"Chaffetz",info:"U.S. House (R) - UT"},
{voteSmartId:104073,firstName:"Ryan K",lastName:"Zinke",info:"U.S. House (R) - MT"},
{voteSmartId:104308,firstName:"Duncan D",lastName:"Hunter",info:"U.S. House (R) - CA"},
{voteSmartId:105566,firstName:"Justin",lastName:"Amash",info:"U.S. House (R) - MI"},
{voteSmartId:106387,firstName:"David",lastName:"Schweikert",info:"U.S. House (R) - AZ"},
{voteSmartId:110252,firstName:"Lee",lastName:"Zeldin",info:"U.S. House (R) - NY"},
{voteSmartId:112062,firstName:"Carl",lastName:"Demaio",info:"U.S. House (R) - CA"},
{voteSmartId:112252,firstName:"Barbara",lastName:"Comstock",info:"U.S. House (R) - VA"},
{voteSmartId:116559,firstName:"Adam",lastName:"Kinzinger",info:"U.S. House (R) - IL"},
{voteSmartId:116570,firstName:"Bobby",lastName:"Schilling",info:"U.S. House (R) - IL"},
{voteSmartId:116906,firstName:"Bill",lastName:"Flores",info:"U.S. House (R) - TX"},
{voteSmartId:116919,firstName:"Blake",lastName:"Farenthold",info:"U.S. House (R) - TX"},
{voteSmartId:117290,firstName:"Andy",lastName:"Barr",info:"U.S. House (R) - KY"},
{voteSmartId:117396,firstName:"David",lastName:"Mckinley",info:"U.S. House (R) - WV"},
{voteSmartId:119463,firstName:"Mike",lastName:"Kelly",info:"U.S. House (R) - PA"},
{voteSmartId:119466,firstName:"Keith J",lastName:"Rothfus",info:"U.S. House (R) - PA"},
{voteSmartId:119474,firstName:"Patrick",lastName:"Meehan",info:"U.S. House (R) - PA"},
{voteSmartId:119478,firstName:"Tom",lastName:"Marino",info:"U.S. House (R) - PA"},
{voteSmartId:120200,firstName:"David",lastName:"Valadao",info:"U.S. House (R) - CA"},
{voteSmartId:120335,firstName:"Larry",lastName:"Bucshon",info:"U.S. House (R) - IN"},
{voteSmartId:120345,firstName:"Todd",lastName:"Young",info:"U.S. House (R) - IN"},
{voteSmartId:120678,firstName:"Jim",lastName:"Renacci",info:"U.S. House (R) - OH"},
{voteSmartId:121782,firstName:"Trey",lastName:"Gowdy",info:"U.S. House (R) - SC"},
{voteSmartId:121807,firstName:"Scott",lastName:"Rigell",info:"U.S. House (R) - VA"},
{voteSmartId:123056,firstName:"Dan",lastName:"Benishek",info:"U.S. House (R) - MI"},
{voteSmartId:123401,firstName:"Billy",lastName:"Long",info:"U.S. House (R) - MO"},
{voteSmartId:123456,firstName:"Chuck",lastName:"Fleischmann",info:"U.S. House (R) - TN"},
{voteSmartId:123491,firstName:"Paul",lastName:"Gosar",info:"U.S. House (R) - AZ"},
{voteSmartId:124329,firstName:"Steve",lastName:"Southerland",info:"U.S. House (R) - FL"},
{voteSmartId:124333,firstName:"Richard",lastName:"Nugent",info:"U.S. House (R) - FL"},
{voteSmartId:124659,firstName:"Steve",lastName:"Fincher",info:"U.S. House (R) - TN"},
{voteSmartId:125023,firstName:"Mike",lastName:"Pompeo",info:"U.S. House (R) - KS"},
{voteSmartId:126238,firstName:"Sean P",lastName:"Duffy",info:"U.S. House (R) - WI"},
{voteSmartId:126240,firstName:"Reid",lastName:"Ribble",info:"U.S. House (R) - WI"},
{voteSmartId:127046,firstName:"Tom",lastName:"Reed",info:"U.S. House (R) - NY"},
{voteSmartId:129529,firstName:"Eric",lastName:"Swalwell",info:"U.S. House (D) - CA"},
{voteSmartId:132068,firstName:"Thomas",lastName:"Massie",info:"U.S. House (R) - KY"},
{voteSmartId:132382,firstName:"Tom",lastName:"Rice",info:"U.S. House (R) - SC"},
{voteSmartId:135326,firstName:"Brad",lastName:"Wenstrup",info:"U.S. House (R) - OH"},
{voteSmartId:135894,firstName:"James",lastName:"Bridenstine",info:"U.S. House (R) - OK"},
{voteSmartId:135898,firstName:"Markwayne",lastName:"Mullin",info:"U.S. House (R) - OK"},
{voteSmartId:135930,firstName:"Chris",lastName:"Stewart",info:"U.S. House (R) - UT"},
{voteSmartId:135957,firstName:"Mia",lastName:"Love",info:"U.S. House (R) - UT"},
{voteSmartId:135988,firstName:"Susan",lastName:"Brooks",info:"U.S. House (R) - IN"},
{voteSmartId:136083,firstName:"Ann L",lastName:"Wagner",info:"U.S. House (R) - MO"},
{voteSmartId:136459,firstName:"Mark R",lastName:"Meadows",info:"U.S. House (R) - NC"},
{voteSmartId:137299,firstName:"Martha",lastName:"Mcsally",info:"U.S. House (R) - AZ"},
{voteSmartId:137630,firstName:"Ron",lastName:"Desantis",info:"U.S. House (R) - FL"},
{voteSmartId:143052,firstName:"David P",lastName:"Joyce",info:"U.S. House (R) - OH"},
{voteSmartId:144699,firstName:"Alieta",lastName:"Eck",info:"U.S. House (R) - NJ"},
{voteSmartId:145943,firstName:"Alex",lastName:"Mooney",info:"U.S. House (R) - WV"},
{voteSmartId:146058,firstName:"Stewart",lastName:"Mills",info:"U.S. House (R) - MN"},
{voteSmartId:146146,firstName:"David",lastName:"Jolly",info:"U.S. House (R) - FL"},
{voteSmartId:146274,firstName:"Gary",lastName:"Palmer",info:"U.S. House (R) - AL"},
{voteSmartId:146290,firstName:"French",lastName:"Hill",info:"U.S. House (R) - AR"},
{voteSmartId:147055,firstName:"John",lastName:"Chapman",info:"U.S. House (R) - MA"},
{voteSmartId:147381,firstName:"John Lee",lastName:"Ratcliffe",info:"U.S. House (R) - TX"},
{voteSmartId:152539,firstName:"Elise",lastName:"Stefanik",info:"U.S. House (R) - NY"},
{voteSmartId:152538,firstName:"Aaron",lastName:"Woolf",info:"U.S. House (D) - NY"},
{voteSmartId:150685,firstName:"Aelea",lastName:"Christofferson",info:"U.S. House (D) - OR"},
{voteSmartId:152112,firstName:"Aimee",lastName:"Belgard",info:"U.S. House (D) - NJ"},
{voteSmartId:146147,firstName:"Alan",lastName:"Cohn",info:"U.S. House (D) - FL"},
{voteSmartId:146010,firstName:"Amanda",lastName:"Renteria",info:"U.S. House (D) - CA"},
{voteSmartId:145975,firstName:"Andrew",lastName:"Walter",info:"U.S. House (R) - AZ"},
{voteSmartId:146237,firstName:"Ann",lastName:"Callis",info:"U.S. House (D) - IL"},
{voteSmartId:152261,firstName:"Anthony",lastName:"Culler",info:"U.S. House (R) - SC"},
{voteSmartId:139613,firstName:"Antonio",lastName:"Diaz",info:"U.S. House (O) - TX"},
{voteSmartId:146150,firstName:"April",lastName:"Freeman",info:"U.S. House (D) - FL"},
{voteSmartId:146032,firstName:"Art",lastName:"Alas",info:"U.S. House (R) - CA"},
{voteSmartId:136548,firstName:"Arthur",lastName:"Rich",info:"U.S. House (R) - NC"},
{voteSmartId:142619,firstName:"Beverly",lastName:"Hires",info:"U.S. House (R) - FL"},
{voteSmartId:146079,firstName:"Bill",lastName:"Tilghman",info:"U.S. House (D) - MD"},
{voteSmartId:147772,firstName:"Bill",lastName:"Ferree",info:"U.S. House (D) - FL"},
{voteSmartId:155111,firstName:"Bill",lastName:"Kelsey",info:"U.S. House (L) - TX"},
{voteSmartId:150678,firstName:"Bob",lastName:"Hart",info:"U.S. House (O) - OH"},
{voteSmartId:153030,firstName:"Bob",lastName:"Dingethal",info:"U.S. House (D) - WA"},
{voteSmartId:152479,firstName:"Bobby",lastName:"Mckenzie",info:"U.S. House (D) - MI"},
{voteSmartId:134948,firstName:"Brad",lastName:"Schneider",info:"U.S. House (D) - IL"},
{voteSmartId:149810,firstName:"Brenda",lastName:"Cleary",info:"U.S. House (D) - NC"},
{voteSmartId:151208,firstName:"Brian",lastName:"Reese",info:"U.S. House (D) - GA"},
{voteSmartId:151208,firstName:"Brian",lastName:"Reese",info:"U.S. House (D) - GA"},
{voteSmartId:153813,firstName:"Brian",lastName:"Lara",info:"U.S. House (R) - FL"},
{voteSmartId:127020,firstName:"Bruce",lastName:"Blakeman",info:"U.S. House (R) - NY"},
{voteSmartId:144638,firstName:"Burton",lastName:"Leflore",info:"U.S. House (D) - AL"},
{voteSmartId:138200,firstName:"Calvin",lastName:"Turnquest",info:"U.S. House (R) - FL"},
{voteSmartId:137676,firstName:"Carlos",lastName:"Curbelo",info:"U.S. House (R) - FL"},
{voteSmartId:146137,firstName:"Carol",lastName:"Platt",info:"U.S. House (R) - FL"},
{voteSmartId:146253,firstName:"Cassie",lastName:"Felder",info:"U.S. House (R) - LA"},
{voteSmartId:127042,firstName:"Chris",lastName:"Gibson",info:"U.S. House (R) - NY"},
{voteSmartId:139770,firstName:"Chris",lastName:"Collins",info:"U.S. House (R) - NY"},
{voteSmartId:152536,firstName:"Chris",lastName:"Day",info:"U.S. House (R) - NY"},
{voteSmartId:150323,firstName:"Clay",lastName:"Aiken",info:"U.S. House (D) - NC"},
{voteSmartId:126032,firstName:"Clint",lastName:"Didier",info:"U.S. House (R) - WA"},
{voteSmartId:151541,firstName:"Craig",lastName:"Bowden",info:"U.S. House (I) - UT"},
{voteSmartId:148899,firstName:"Curt",lastName:"Clawson",info:"U.S. House (R) - FL"},
{voteSmartId:135118,firstName:"Curtis",lastName:"Railey",info:"U.S. House (I) - AL"},
{voteSmartId:133474,firstName:"Dan",lastName:"Lavallee",info:"U.S. House (D) - PA"},
{voteSmartId:135123,firstName:"Dan",lastName:"Bongino",info:"U.S. House (R) - MD"},
{voteSmartId:136102,firstName:"Dan",lastName:"Kildee",info:"U.S. House (D) - MI"},
{voteSmartId:146070,firstName:"Dan",lastName:"Innis",info:"U.S. House (R) - NH"},
{voteSmartId:152494,firstName:"Dan",lastName:"Shores",info:"U.S. House (R) - MA"},
{voteSmartId:146118,firstName:"Dave",lastName:"Wallace",info:"U.S. House (R) - MD"},
{voteSmartId:146120,firstName:"Dave",lastName:"Peiser",info:"U.S. House (D) - CA"},
{voteSmartId:152270,firstName:"Dave",lastName:"Brat",info:"U.S. House (R) - VA"},
{voteSmartId:152477,firstName:"Dave",lastName:"Trott",info:"U.S. House (R) - MI"},
{voteSmartId:146154,firstName:"David",lastName:"Wagie",info:"U.S. House (R) - FL"},
{voteSmartId:146175,firstName:"David",lastName:"Smith",info:"U.S. House (R) - FL"},
{voteSmartId:146180,firstName:"David",lastName:"Koller",info:"U.S. House (D) - FL"},
{voteSmartId:152458,firstName:"Dean",lastName:"Vanderstelt",info:"U.S. House (D) - MI"},
{voteSmartId:152482,firstName:"Debbie",lastName:"Dingell",info:"U.S. House (D) - MI"},
{voteSmartId:149580,firstName:"Dennis",lastName:"Crawford",info:"U.S. House (D) - NE"},
{voteSmartId:139617,firstName:"Don",lastName:"Cook",info:"U.S. House (O) - TX"},
{voteSmartId:147355,firstName:"Don",lastName:"Brown",info:"U.S. House (D) - TX"},
{voteSmartId:151619,firstName:"Doug",lastName:"Owens",info:"U.S. House (D) - UT"},
{voteSmartId:151800,firstName:"Drew",lastName:"Leavens",info:"U.S. House (D) - CA"},
{voteSmartId:135665,firstName:"Ed",lastName:"Rankin",info:"U.S. House (L) - TX"},
{voteSmartId:146158,firstName:"Ed",lastName:"Macdougall",info:"U.S. House (R) - FL"},
{voteSmartId:155102,firstName:"Ed",lastName:"Colliver",info:"U.S. House (L) - TX"},
{voteSmartId:151710,firstName:"Elan",lastName:"Carr",info:"U.S. House (R) - CA"},
{voteSmartId:146105,firstName:"Elisabeth",lastName:"Jensen",info:"U.S. House (D) - KY"},
{voteSmartId:155112,firstName:"Emily",lastName:"Pivoda",info:"U.S. House (L) - TX"},
{voteSmartId:146241,firstName:"Eric",lastName:"Thorsland",info:"U.S. House (D) - IL"},
{voteSmartId:146266,firstName:"Erick",lastName:"Wright",info:"U.S. House (I) - AL"},
{voteSmartId:150799,firstName:"Erin",lastName:"Mcclelland",info:"U.S. House (D) - PA"},
{voteSmartId:145947,firstName:"Forrest",lastName:"Dunbar",info:"U.S. House (D) - AK"},
{voteSmartId:147368,firstName:"Frank",lastName:"Perez",info:"U.S. House (D) - TX"},
{voteSmartId:135325,firstName:"Fred",lastName:"Kundrata",info:"U.S. House (D) - OH"},
{voteSmartId:126941,firstName:"Gary",lastName:"Lambert",info:"U.S. House (R) - NH"},
{voteSmartId:143022,firstName:"Gary",lastName:"Landrieu",info:"U.S. House (D) - LA"},
{voteSmartId:145964,firstName:"Gary",lastName:"Kiehne",info:"U.S. House (R) - AZ"},
{voteSmartId:136462,firstName:"George",lastName:"Holding",info:"U.S. House (R) - NC"},
{voteSmartId:139849,firstName:"George",lastName:"Gluck",info:"U.S. House (O) - MD"},
{voteSmartId:152476,firstName:"George",lastName:"Brikho",info:"U.S. House (R) - MI"},
{voteSmartId:153018,firstName:"George",lastName:"Leing",info:"U.S. House (R) - CO"},
{voteSmartId:155109,firstName:"Gerald",lastName:"Fowler",info:"U.S. House (L) - TX"},
{voteSmartId:155014,firstName:"Grant",lastName:"Doherty",info:"U.S. House (I) - CO"},
{voteSmartId:151214,firstName:"Greg",lastName:"Duke",info:"U.S. House (R) - GA"},
{voteSmartId:151214,firstName:"Greg",lastName:"Duke",info:"U.S. House (R) - GA"},
{voteSmartId:146129,firstName:"Gwen",lastName:"Graham",info:"U.S. House (D) - FL"},
{voteSmartId:145978,firstName:"Heidi",lastName:"Hall",info:"U.S. House (D) - CA"},
{voteSmartId:153878,firstName:"Henry",lastName:"Lawrence",info:"U.S. House (D) - FL"},
{voteSmartId:153796,firstName:"Howard",lastName:"Lawson",info:"U.S. House (I) - FL"},
{voteSmartId:135597,firstName:"Hugh",lastName:"Chauvin",info:"U.S. House (L) - TX"},
{voteSmartId:146080,firstName:"Ian",lastName:"Schlakman",info:"U.S. House (O) - MD"},
{voteSmartId:151467,firstName:"Isaac",lastName:"Misiuk",info:"U.S. House (R) - ME"},
{voteSmartId:153797,firstName:"Jake",lastName:"Rush",info:"U.S. House (R) - FL"},
{voteSmartId:135598,firstName:"James",lastName:"Cargas",info:"U.S. House (D) - TX"},
{voteSmartId:135662,firstName:"James",lastName:"Stanczak",info:"U.S. House (L) - TX"},
{voteSmartId:146123,firstName:"James",lastName:"Kimber",info:"U.S. House (D) - CA"},
{voteSmartId:145958,firstName:"Jason",lastName:"Ritchie",info:"U.S. House (D) - WA"},
{voteSmartId:146277,firstName:"Jason",lastName:"Reeves",info:"U.S. House (L) - TX"},
{voteSmartId:150688,firstName:"Jason",lastName:"Yates",info:"U.S. House (R) - OR"},
{voteSmartId:146151,firstName:"Jean",lastName:"Enright",info:"U.S. House (D) - FL"},
{voteSmartId:154777,firstName:"Jeffrey",lastName:"Carson",info:"U.S. House (L) - VA"},
{voteSmartId:146119,firstName:"Jennifer",lastName:"Whelan",info:"U.S. House (L) - TX"},
{voteSmartId:152453,firstName:"Jerry",lastName:"Cannon",info:"U.S. House (D) - MI"},
{voteSmartId:146027,firstName:"Jim",lastName:"Hagedorn",info:"U.S. House (R) - MN"},
{voteSmartId:146169,firstName:"Jim",lastName:"Mowrer",info:"U.S. House (D) - IA"},
{voteSmartId:147769,firstName:"Jim",lastName:"Fischer",info:"U.S. House (R) - NY"},
{voteSmartId:146190,firstName:"Joe",lastName:"Bock",info:"U.S. House (D) - IN"},
{voteSmartId:152789,firstName:"Joe",lastName:"Perske",info:"U.S. House (D) - MN"},
{voteSmartId:152942,firstName:"Joe",lastName:"Pakootas",info:"U.S. House (D) - WA"},
{voteSmartId:153831,firstName:"Joe",lastName:"Martinez",info:"U.S. House (R) - FL"},
{voteSmartId:135822,firstName:"John",lastName:"Adams",info:"U.S. House (R) - OH"},
{voteSmartId:149631,firstName:"John",lastName:"Dale",info:"U.S. House (D) - IN"},
{voteSmartId:152546,firstName:"John",lastName:"Katko",info:"U.S. House (R) - NY"},
{voteSmartId:154123,firstName:"John",lastName:"Devine",info:"U.S. House (D) - MA"},
{voteSmartId:135620,firstName:"Johnny",lastName:"Partain",info:"U.S. House (L) - TX"},
{voteSmartId:155110,firstName:"Johnny",lastName:"Johnson",info:"U.S. House (L) - TX"},
{voteSmartId:146136,firstName:"Jorge",lastName:"Bonilla",info:"U.S. House (R) - FL"},
{voteSmartId:154657,firstName:"Josh",lastName:"Dill",info:"U.S. House (O) - IL"},
{voteSmartId:137669,firstName:"Juan",lastName:"Garcia",info:"U.S. House (R) - FL"},
{voteSmartId:127653,firstName:"Kathleen",lastName:"Rice",info:"U.S. House (D) - NY"},
{voteSmartId:153500,firstName:"Kelly",lastName:"Westlund",info:"U.S. House (D) - WI"},
{voteSmartId:151224,firstName:"Ken",lastName:"Dious",info:"U.S. House (D) - GA"},
{voteSmartId:151224,firstName:"Ken",lastName:"Dious",info:"U.S. House (D) - GA"},
{voteSmartId:150909,firstName:"Kevin",lastName:"Strouse",info:"U.S. House (D) - PA"},
{voteSmartId:147397,firstName:"Larry",lastName:"Smith",info:"U.S. House (R) - TX"},
{voteSmartId:151887,firstName:"Larry",lastName:"Wilske",info:"U.S. House (R) - CA"},
{voteSmartId:146254,firstName:"Laura",lastName:"Fjeld",info:"U.S. House (D) - NC"},
{voteSmartId:145987,firstName:"Louie",lastName:"Minor",info:"U.S. House (D) - TX"},
{voteSmartId:146145,firstName:"Lucas",lastName:"Overby",info:"U.S. House (L) - FL"},
{voteSmartId:153828,firstName:"Luis",lastName:"Fernandez",info:"U.S. House (I) - FL"},
{voteSmartId:149723,firstName:"Luther",lastName:"Lee",info:"U.S. House (I) - FL"},
{voteSmartId:149854,firstName:"Marek",lastName:"Tyszkiewicz",info:"U.S. House (D) - OH"},
{voteSmartId:146122,firstName:"Margie",lastName:"Wakefield",info:"U.S. House (D) - KS"},
{voteSmartId:146298,firstName:"Marisa",lastName:"Defranco",info:"U.S. House (D) - MA"},
{voteSmartId:153795,firstName:"Mark",lastName:"Wichern",info:"U.S. House (I) - FL"},
{voteSmartId:136236,firstName:"Matt",lastName:"Cartwright",info:"U.S. House (D) - PA"},
{voteSmartId:143349,firstName:"Matthew",lastName:"Corey",info:"U.S. House (R) - CT"},
{voteSmartId:154779,firstName:"Micah",lastName:"Edmond",info:"U.S. House (R) - VA"},
{voteSmartId:127075,firstName:"Michael",lastName:"Grimm",info:"U.S. House (R) - NY"},
{voteSmartId:139616,firstName:"Michael",lastName:"Cary",info:"U.S. House (O) - TX"},
{voteSmartId:145994,firstName:"Michael",lastName:"Eggman",info:"U.S. House (D) - CA"},
{voteSmartId:146015,firstName:"Michael",lastName:"Wager",info:"U.S. House (D) - OH"},
{voteSmartId:146103,firstName:"Michael",lastName:"Macfarlane",info:"U.S. House (R) - KY"},
{voteSmartId:146140,firstName:"Michael",lastName:"Mckenna",info:"U.S. House (D) - FL"},
{voteSmartId:146283,firstName:"Michael",lastName:"Mason",info:"U.S. House (D) - IL"},
{voteSmartId:155116,firstName:"Mike",lastName:"Kolls",info:"U.S. House (L) - TX"},
{voteSmartId:127041,firstName:"Nan",lastName:"Hayworth",info:"U.S. House (R) - NY"},
{voteSmartId:150056,firstName:"Nancy",lastName:"Hoyt",info:"U.S. House (R) - MD"},
{voteSmartId:137157,firstName:"Natale",lastName:"Stracuzzi",info:"U.S. House (O) - DC"},
{voteSmartId:145979,firstName:"Neal",lastName:"Marchbanks",info:"U.S. House (D) - TX"},
{voteSmartId:145939,firstName:"Nick",lastName:"Casey",info:"U.S. House (D) - WV"},
{voteSmartId:147360,firstName:"Nick",lastName:"Haynes",info:"U.S. House (D) - TX"},
{voteSmartId:147287,firstName:"Niko",lastName:"Letsos",info:"U.S. House (D) - TX"},
{voteSmartId:135641,firstName:"Patrick",lastName:"Mcgehearty",info:"U.S. House (D) - TX"},
{voteSmartId:146030,firstName:"Paula",lastName:"Overby",info:"U.S. House (D) - MN"},
{voteSmartId:146138,firstName:"Peter",lastName:"Vivaldi",info:"U.S. House (R) - FL"},
{voteSmartId:146113,firstName:"Quentin",lastName:"Anderson",info:"U.S. House (D) - LA"},
{voteSmartId:146242,firstName:"Randall",lastName:"Olsen",info:"U.S. House (D) - IL"},
{voteSmartId:136407,firstName:"Raul",lastName:"Ruiz",info:"U.S. House (D) - CA"},
{voteSmartId:154436,firstName:"Rhue",lastName:"Reis",info:"U.S. House (R) - RI"},
{voteSmartId:136448,firstName:"Richard",lastName:"Hudson",info:"U.S. House (R) - NC"},
{voteSmartId:146114,firstName:"Richard",lastName:"Lieberman",info:"U.S. House (D) - LA"},
{voteSmartId:154739,firstName:"Richard",lastName:"Murphy",info:"U.S. House (I) - ME"},
{voteSmartId:138505,firstName:"Rick",lastName:"Nolan",info:"U.S. House (D) - MN"},
{voteSmartId:155114,firstName:"Rob",lastName:"Lapham",info:"U.S. House (L) - TX"},
{voteSmartId:146284,firstName:"Robert",lastName:"Bumpers",info:"U.S. House (R) - IL"},
{voteSmartId:150570,firstName:"Robert",lastName:"Fry",info:"U.S. House (D) - OH"},
{voteSmartId:135714,firstName:"Rod",lastName:"Blum",info:"U.S. House (R) - IA"},
{voteSmartId:137292,firstName:"Ron",lastName:"Barber",info:"U.S. House (D) - AZ"},
{voteSmartId:146102,firstName:"Ron",lastName:"Leach",info:"U.S. House (D) - KY"},
{voteSmartId:155108,firstName:"Roxanne",lastName:"Simonson",info:"U.S. House (L) - TX"},
{voteSmartId:152115,firstName:"Roy",lastName:"Cho",info:"U.S. House (D) - NJ"},
{voteSmartId:155115,firstName:"Ruben",lastName:"Corvalan",info:"U.S. House (L) - TX"},
{voteSmartId:133557,firstName:"Ryan",lastName:"Costello",info:"U.S. House (R) - PA"},
{voteSmartId:155105,firstName:"Ryan",lastName:"Lange",info:"U.S. House (L) - TX"},
{voteSmartId:155106,firstName:"Ryan",lastName:"Shields",info:"U.S. House (L) - TX"},
{voteSmartId:135347,firstName:"Scott",lastName:"Wharton",info:"U.S. House (D) - OH"},
{voteSmartId:142329,firstName:"Scott",lastName:"Soffen",info:"U.S. House (L) - MD"},
{voteSmartId:135628,firstName:"Sean",lastName:"Seibert",info:"U.S. House (R) - TX"},
{voteSmartId:152537,firstName:"Sean",lastName:"Eldridge",info:"U.S. House (D) - NY"},
{voteSmartId:146299,firstName:"Seth",lastName:"Moulton",info:"U.S. House (D) - MA"},
{voteSmartId:146282,firstName:"Sharon",lastName:"Brannigan",info:"U.S. House (R) - IL"},
{voteSmartId:149636,firstName:"Shawn",lastName:"Denney",info:"U.S. House (D) - IN"},
{voteSmartId:146176,firstName:"Shayan",lastName:"Modarres",info:"U.S. House (D) - FL"},
{voteSmartId:135589,firstName:"Shirley",lastName:"Mckellar",info:"U.S. House (D) - TX"},
{voteSmartId:126272,firstName:"Suzan",lastName:"Delbene",info:"U.S. House (D) - WA"},
{voteSmartId:152271,firstName:"Suzanne",lastName:"Patrick",info:"U.S. House (D) - VA"},
{voteSmartId:154785,firstName:"Suzanne",lastName:"Scholte",info:"U.S. House (R) - VA"},
{voteSmartId:137622,firstName:"Ted",lastName:"Yoho",info:"U.S. House (R) - FL"},
{voteSmartId:152481,firstName:"Terry",lastName:"Bowman",info:"U.S. House (R) - MI"},
{voteSmartId:151219,firstName:"Thomas",lastName:"Wight",info:"U.S. House (D) - GA"},
{voteSmartId:151219,firstName:"Thomas",lastName:"Wight",info:"U.S. House (D) - GA"},
{voteSmartId:146131,firstName:"Thuy",lastName:"Lowe",info:"U.S. House (R) - FL"},
{voteSmartId:146109,firstName:"Tim",lastName:"Sheridan",info:"U.S. House (D) - CA"},
{voteSmartId:146012,firstName:"Tom",lastName:"Poetter",info:"U.S. House (D) - OH"},
{voteSmartId:149641,firstName:"Tom",lastName:"Spangler",info:"U.S. House (D) - IN"},
{voteSmartId:129306,firstName:"Tulsi",lastName:"Gabbard",info:"U.S. House (D) - HI"},
{voteSmartId:145379,firstName:"Vance",lastName:"Mcallister",info:"U.S. House (R) - LA"},
{voteSmartId:150342,firstName:"Vince",lastName:"Coakley",info:"U.S. House (R) - NC"},
{voteSmartId:149731,firstName:"Wes",lastName:"Neuman",info:"U.S. House (D) - FL"},
{voteSmartId:147367,firstName:"Wesley",lastName:"Reed",info:"U.S. House (D) - TX"},
{voteSmartId:142,firstName:"Brad",lastName:"Sherman",info:"U.S. House (D) - CA"},
{voteSmartId:203,firstName:"Loretta",lastName:"Sanchez",info:"U.S. House (D) - CA"},
{voteSmartId:233,firstName:"Danny K",lastName:"Davis",info:"U.S. House (D) - IL"},
{voteSmartId:291,firstName:"Ruben",lastName:"Hinojosa",info:"U.S. House (D) - TX"},
{voteSmartId:334,firstName:"Kay",lastName:"Granger",info:"U.S. House (R) - TX"},
{voteSmartId:345,firstName:"Elijah E",lastName:"Cummings",info:"U.S. House (D) - MD"},
{voteSmartId:360,firstName:"Brian",lastName:"Babin",info:"U.S. House (R) - TX"},
{voteSmartId:367,firstName:"Earl",lastName:"Blumenauer",info:"U.S. House (D) - OR"},
{voteSmartId:478,firstName:"Bill Jr",lastName:"Pascrell",info:"U.S. House (D) - NJ"},
{voteSmartId:552,firstName:"James P",lastName:"Mcgovern",info:"U.S. House (D) - MA"},
{voteSmartId:553,firstName:"John F",lastName:"Tierney",info:"U.S. House (D) - MA"},
{voteSmartId:561,firstName:"Diana",lastName:"Degette",info:"U.S. House (D) - CO"},
{voteSmartId:630,firstName:"Ron",lastName:"Kind",info:"U.S. House (D) - WI"},
{voteSmartId:694,firstName:"Grant",lastName:"Lally",info:"U.S. House (R) - NY"},
{voteSmartId:775,firstName:"Eleanor Holmes",lastName:"Norton",info:"U.S. House (D) - DC"},
{voteSmartId:845,firstName:"Adam",lastName:"Smith",info:"U.S. House (D) - WA"},
{voteSmartId:1516,firstName:"Ted",lastName:"Lieu",info:"U.S. House (D) - CA"},
{voteSmartId:1707,firstName:"Don",lastName:"Beyer",info:"U.S. House (D) - VA"},
{voteSmartId:2427,firstName:"Joyce",lastName:"Beatty",info:"U.S. House (D) - OH"},
{voteSmartId:2519,firstName:"Robert A",lastName:"Brady",info:"U.S. House (D) - PA"},
{voteSmartId:2602,firstName:"Mark",lastName:"Takai",info:"U.S. House (D) - HI"},
{voteSmartId:2629,firstName:"Dina",lastName:"Titus",info:"U.S. House (D) - NV"},
{voteSmartId:2653,firstName:"Edwin G",lastName:"Perlmutter",info:"U.S. House (D) - CO"},
{voteSmartId:3457,firstName:"Gwen",lastName:"Moore",info:"U.S. House (D) - WI"},
{voteSmartId:3564,firstName:"Mike",lastName:"Thompson",info:"U.S. House (D) - CA"},
{voteSmartId:3577,firstName:"Jim",lastName:"Costa",info:"U.S. House (D) - CA"},
{voteSmartId:3812,firstName:"Betty",lastName:"Mccollum",info:"U.S. House (D) - MN"},
{voteSmartId:3985,firstName:"Joe",lastName:"Wilson",info:"U.S. House (R) - SC"},
{voteSmartId:4295,firstName:"Joseph",lastName:"Crowley",info:"U.S. House (D) - NY"},
{voteSmartId:4360,firstName:"Gregory W",lastName:"Meeks",info:"U.S. House (D) - NY"},
{voteSmartId:4403,firstName:"Paul",lastName:"Tonko",info:"U.S. House (D) - NY"},
{voteSmartId:4443,firstName:"Leonard",lastName:"Lance",info:"U.S. House (R) - NJ"},
{voteSmartId:4607,firstName:"Bill",lastName:"Bailey",info:"U.S. House (D) - IN"},
{voteSmartId:4743,firstName:"Bill",lastName:"Keating",info:"U.S. House (D) - MA"},
{voteSmartId:4760,firstName:"Richard",lastName:"Tisei",info:"U.S. House (R) - MA"},
{voteSmartId:4844,firstName:"Stephen F",lastName:"Lynch",info:"U.S. House (D) - MA"},
{voteSmartId:5146,firstName:"Randy",lastName:"Forbes",info:"U.S. House (R) - VA"},
{voteSmartId:5486,firstName:"Henry",lastName:"Cuellar",info:"U.S. House (D) - TX"},
{voteSmartId:5505,firstName:"Pete",lastName:"Gallego",info:"U.S. House (D) - TX"},
{voteSmartId:5705,firstName:"Mike D",lastName:"Rogers",info:"U.S. House (R) - AL"},
{voteSmartId:6098,firstName:"Hollen, Chris",lastName:"Van Hollen",info:"U.S. House (D) - MD"},
{voteSmartId:6387,firstName:"Jan",lastName:"Schakowsky",info:"U.S. House (D) - IL"},
{voteSmartId:6530,firstName:"Pat",lastName:"Murphy",info:"U.S. House (D) - IA"},
{voteSmartId:6586,firstName:"Chellie",lastName:"Pingree",info:"U.S. House (D) - ME"},
{voteSmartId:7349,firstName:"David",lastName:"Cicilline",info:"U.S. House (D) - RI"},
{voteSmartId:8001,firstName:"Lynn A",lastName:"Westmoreland",info:"U.S. House (R) - GA"},
{voteSmartId:8102,firstName:"Lois J",lastName:"Frankel",info:"U.S. House (D) - FL"},
{voteSmartId:8168,firstName:"Susan A",lastName:"Davis",info:"U.S. House (D) - CA"},
{voteSmartId:8315,firstName:"Barbara",lastName:"Lee",info:"U.S. House (D) - CA"},
{voteSmartId:8393,firstName:"Grace",lastName:"Napolitano",info:"U.S. House (D) - CA"},
{voteSmartId:8425,firstName:"Jackie",lastName:"Speier",info:"U.S. House (D) - CA"},
{voteSmartId:8967,firstName:"William L Jr",lastName:"Clay",info:"U.S. House (D) - MO"},
{voteSmartId:9425,firstName:"Sam",lastName:"Graves",info:"U.S. House (R) - MO"},
{voteSmartId:9489,firstName:"Adam",lastName:"Schiff",info:"U.S. House (D) - CA"},
{voteSmartId:9674,firstName:"Mike",lastName:"Honda",info:"U.S. House (D) - CA"},
{voteSmartId:9754,firstName:"Tony",lastName:"Cardenas",info:"U.S. House (D) - CA"},
{voteSmartId:10813,firstName:"Kurt",lastName:"Schrader",info:"U.S. House (D) - OR"},
{voteSmartId:12537,firstName:"Mark",lastName:"Amodei",info:"U.S. House (R) - NV"},
{voteSmartId:12695,firstName:"Vic",lastName:"Meyers",info:"U.S. House (D) - CO"},
{voteSmartId:13444,firstName:"Torrey",lastName:"Westrom",info:"U.S. House (R) - MN"},
{voteSmartId:15107,firstName:"Vincent Jr",lastName:"Cogliano",info:"U.S. House (R) - MA"},
{voteSmartId:16469,firstName:"Alan",lastName:"Lowenthal",info:"U.S. House (D) - CA"},
{voteSmartId:16472,firstName:"Doug",lastName:"Ose",info:"U.S. House (R) - CA"},
{voteSmartId:16539,firstName:"Judy",lastName:"Chu",info:"U.S. House (D) - CA"},
{voteSmartId:16886,firstName:"Lois",lastName:"Capps",info:"U.S. House (D) - CA"},
{voteSmartId:17276,firstName:"Jeff",lastName:"Miller",info:"U.S. House (R) - FL"},
{voteSmartId:17318,firstName:"Gus",lastName:"Bilirakis",info:"U.S. House (R) - FL"},
{voteSmartId:17319,firstName:"Frederica",lastName:"Wilson",info:"U.S. House (D) - FL"},
{voteSmartId:17350,firstName:"Joe",lastName:"Kaufman",info:"U.S. House (R) - FL"},
{voteSmartId:18109,firstName:"Shirley",lastName:"Ringo",info:"U.S. House (D) - ID"},
{voteSmartId:18883,firstName:"Michael E",lastName:"Capuano",info:"U.S. House (D) - MA"},
{voteSmartId:19653,firstName:"Pam",lastName:"Byrnes",info:"U.S. House (D) - MI"},
{voteSmartId:21689,firstName:"Lloyd",lastName:"Doggett",info:"U.S. House (D) - TX"},
{voteSmartId:21692,firstName:"Lee, Sheila",lastName:"Jackson Lee",info:"U.S. House (D) - TX"},
{voteSmartId:21706,firstName:"Mac",lastName:"Thornberry",info:"U.S. House (R) - TX"},
{voteSmartId:21785,firstName:"Walter B Jr",lastName:"Jones",info:"U.S. House (R) - NC"},
{voteSmartId:21790,firstName:"Steve",lastName:"Chabot",info:"U.S. House (R) - OH"},
{voteSmartId:21845,firstName:"Ken",lastName:"Ashby",info:"U.S. House (L) - TX"},
{voteSmartId:21850,firstName:"Chaka",lastName:"Fattah",info:"U.S. House (D) - PA"},
{voteSmartId:21890,firstName:"Frank A",lastName:"Lobiondo",info:"U.S. House (R) - NJ"},
{voteSmartId:21899,firstName:"Zoe",lastName:"Lofgren",info:"U.S. House (D) - CA"},
{voteSmartId:22337,firstName:"Mark",lastName:"Takano",info:"U.S. House (D) - CA"},
{voteSmartId:22510,firstName:"Albio",lastName:"Sires",info:"U.S. House (D) - NJ"},
{voteSmartId:23127,firstName:"Brian M",lastName:"Higgins",info:"U.S. House (D) - NY"},
{voteSmartId:23377,firstName:"Pete",lastName:"Crossland",info:"U.S. House (D) - OH"},
{voteSmartId:24280,firstName:"Bill",lastName:"Posey",info:"U.S. House (R) - FL"},
{voteSmartId:24301,firstName:"Debbie Wasserman",lastName:"Schultz",info:"U.S. House (D) - FL"},
{voteSmartId:24302,firstName:"Daniel",lastName:"Webster",info:"U.S. House (R) - FL"},
{voteSmartId:24312,firstName:"Mario",lastName:"Diaz-Balart",info:"U.S. House (R) - FL"},
{voteSmartId:24340,firstName:"Steve",lastName:"Cohen",info:"U.S. House (D) - TN"},
{voteSmartId:24799,firstName:"Bonnie Watson",lastName:"Coleman",info:"U.S. House (D) - NJ"},
{voteSmartId:25795,firstName:"John",lastName:"Foust",info:"U.S. House (D) - VA"},
{voteSmartId:26238,firstName:"Mark",lastName:"Pocan",info:"U.S. House (D) - WI"},
{voteSmartId:26717,firstName:"Don",lastName:"Young",info:"U.S. House (R) - AK"},
{voteSmartId:26732,firstName:"Nancy",lastName:"Pelosi",info:"U.S. House (D) - CA"},
{voteSmartId:26741,firstName:"Anna",lastName:"Eshoo",info:"U.S. House (D) - CA"},
{voteSmartId:26745,firstName:"Sam",lastName:"Farr",info:"U.S. House (D) - CA"},
{voteSmartId:26754,firstName:"Xavier",lastName:"Becerra",info:"U.S. House (D) - CA"},
{voteSmartId:26759,firstName:"Maxine",lastName:"Waters",info:"U.S. House (D) - CA"},
{voteSmartId:26763,firstName:"Dana",lastName:"Rohrabacher",info:"U.S. House (R) - CA"},
{voteSmartId:26766,firstName:"Lucille",lastName:"Roybal-Allard",info:"U.S. House (D) - CA"},
{voteSmartId:26777,firstName:"Ken",lastName:"Calvert",info:"U.S. House (R) - CA"},
{voteSmartId:26788,firstName:"Rosa L",lastName:"Delauro",info:"U.S. House (D) - CT"},
{voteSmartId:26797,firstName:"Corrine",lastName:"Brown",info:"U.S. House (D) - FL"},
{voteSmartId:26798,firstName:"Alcee L",lastName:"Hastings",info:"U.S. House (D) - FL"},
{voteSmartId:26805,firstName:"John L",lastName:"Mica",info:"U.S. House (R) - FL"},
{voteSmartId:26815,firstName:"Ileana",lastName:"Ros-Lehtinen",info:"U.S. House (R) - FL"},
{voteSmartId:26831,firstName:"Bobby L",lastName:"Rush",info:"U.S. House (D) - IL"},
{voteSmartId:26841,firstName:"Luis V",lastName:"Gutierrez",info:"U.S. House (D) - IL"},
{voteSmartId:26851,firstName:"Pete",lastName:"Visclosky",info:"U.S. House (D) - IN"},
{voteSmartId:26875,firstName:"Hal",lastName:"Rogers",info:"U.S. House (R) - KY"},
{voteSmartId:26890,firstName:"Steny H",lastName:"Hoyer",info:"U.S. House (D) - MD"},
{voteSmartId:26895,firstName:"Richard E",lastName:"Neal",info:"U.S. House (D) - MA"},
{voteSmartId:26904,firstName:"John Jr",lastName:"Conyers",info:"U.S. House (D) - MI"},
{voteSmartId:26918,firstName:"Sander",lastName:"Levin",info:"U.S. House (D) - MI"},
{voteSmartId:26929,firstName:"Bennie G",lastName:"Thompson",info:"U.S. House (D) - MS"},
{voteSmartId:26951,firstName:"Frank Jr",lastName:"Pallone",info:"U.S. House (D) - NJ"},
{voteSmartId:26968,firstName:"Pete",lastName:"King",info:"U.S. House (R) - NY"},
{voteSmartId:26972,firstName:"Eliot L",lastName:"Engel",info:"U.S. House (D) - NY"},
{voteSmartId:26975,firstName:"Nydia M",lastName:"Velazquez",info:"U.S. House (D) - NY"},
{voteSmartId:26978,firstName:"Carolyn B",lastName:"Maloney",info:"U.S. House (D) - NY"},
{voteSmartId:26979,firstName:"Charles B",lastName:"Rangel",info:"U.S. House (D) - NY"},
{voteSmartId:26980,firstName:"Jerrold",lastName:"Nadler",info:"U.S. House (D) - NY"},
{voteSmartId:26982,firstName:"Nita M",lastName:"Lowey",info:"U.S. House (D) - NY"},
{voteSmartId:26991,firstName:"Louise M",lastName:"Slaughter",info:"U.S. House (D) - NY"},
{voteSmartId:27016,firstName:"Marcy",lastName:"Kaptur",info:"U.S. House (D) - OH"},
{voteSmartId:27032,firstName:"Frank D",lastName:"Lucas",info:"U.S. House (R) - OK"},
{voteSmartId:27037,firstName:"Peter",lastName:"Defazio",info:"U.S. House (D) - OR"},
{voteSmartId:27066,firstName:"James E",lastName:"Clyburn",info:"U.S. House (D) - SC"},
{voteSmartId:27069,firstName:"John J Jr",lastName:"Duncan",info:"U.S. House (R) - TN"},
{voteSmartId:27082,firstName:"Joe",lastName:"Barton",info:"U.S. House (R) - TX"},
{voteSmartId:27098,firstName:"Eddie Bernice",lastName:"Johnson",info:"U.S. House (D) - TX"},
{voteSmartId:27100,firstName:"Gene",lastName:"Green",info:"U.S. House (D) - TX"},
{voteSmartId:27117,firstName:"Bobby",lastName:"Scott",info:"U.S. House (D) - VA"},
{voteSmartId:27133,firstName:"Nick",lastName:"Rahall",info:"U.S. House (D) - WV"},
{voteSmartId:27584,firstName:"Bradley",lastName:"Byrne",info:"U.S. House (R) - AL"},
{voteSmartId:27740,firstName:"Jackie",lastName:"Mcpherson",info:"U.S. House (D) - AR"},
{voteSmartId:28253,firstName:"Raul M",lastName:"Grijalva",info:"U.S. House (D) - AZ"},
{voteSmartId:28338,firstName:"Kyrsten",lastName:"Sinema",info:"U.S. House (D) - AZ"},
{voteSmartId:28399,firstName:"Trent",lastName:"Franks",info:"U.S. House (R) - AZ"},
{voteSmartId:28425,firstName:"Ann",lastName:"Kirkpatrick",info:"U.S. House (D) - AZ"},
{voteSmartId:28593,firstName:"Doris O",lastName:"Matsui",info:"U.S. House (D) - CA"},
{voteSmartId:28963,firstName:"Karen",lastName:"Bass",info:"U.S. House (D) - CA"},
{voteSmartId:29100,firstName:"Juan",lastName:"Vargas",info:"U.S. House (D) - CA"},
{voteSmartId:29473,firstName:"Ro",lastName:"Khanna",info:"U.S. House (D) - CA"},
{voteSmartId:29474,firstName:"Jerry",lastName:"Mcnerney",info:"U.S. House (D) - CA"},
{voteSmartId:29664,firstName:"John",lastName:"Garamendi",info:"U.S. House (D) - CA"},
{voteSmartId:29674,firstName:"Linda",lastName:"Sanchez",info:"U.S. House (D) - CA"},
{voteSmartId:30146,firstName:"Andrew",lastName:"Romanoff",info:"U.S. House (D) - CO"},
{voteSmartId:30333,firstName:"Joe",lastName:"Courtney",info:"U.S. House (D) - CT"},
{voteSmartId:32085,firstName:"Buddy",lastName:"Carter",info:"U.S. House (R) - GA"},
{voteSmartId:33384,firstName:"Robin",lastName:"Kelly",info:"U.S. House (D) - IL"},
{voteSmartId:33692,firstName:"Daniel",lastName:"Lipinski",info:"U.S. House (D) - IL"},
{voteSmartId:34330,firstName:"Andy",lastName:"Horning",info:"U.S. House (L) - IN"},
{voteSmartId:35384,firstName:"Cedric",lastName:"Richmond",info:"U.S. House (D) - LA"},
{voteSmartId:35858,firstName:"Katherine",lastName:"Clark",info:"U.S. House (D) - MA"},
{voteSmartId:36130,firstName:"Dutch",lastName:"Ruppersberger",info:"U.S. House (D) - MD"},
{voteSmartId:36450,firstName:"Carrogan",lastName:"Vaughn",info:"U.S. House (R) - MD"},
{voteSmartId:36658,firstName:"Emily",lastName:"Cain",info:"U.S. House (D) - ME"},
{voteSmartId:38894,firstName:"Tom",lastName:"Emmer",info:"U.S. House (R) - MN"},
{voteSmartId:38982,firstName:"Keith",lastName:"Ellison",info:"U.S. House (D) - MN"},
{voteSmartId:39507,firstName:"Emanuel",lastName:"Cleaver",info:"U.S. House (D) - MO"},
{voteSmartId:41077,firstName:"G K",lastName:"Butterfield",info:"U.S. House (D) - NC"},
{voteSmartId:41929,firstName:"Jeff",lastName:"Fortenberry",info:"U.S. House (R) - NE"},
{voteSmartId:43293,firstName:"Bill Jr",lastName:"Hughes",info:"U.S. House (D) - NJ"},
{voteSmartId:43293,firstName:"William J",lastName:"Hughes",info:"U.S. House (D) - NJ"},
{voteSmartId:43350,firstName:"Pablo",lastName:"Olivera",info:"U.S. House (O) - NJ"},
{voteSmartId:44064,firstName:"Steven",lastName:"Horsford",info:"U.S. House (D) - NV"},
{voteSmartId:44518,firstName:"Timothy H",lastName:"Bishop",info:"U.S. House (D) - NY"},
{voteSmartId:44741,firstName:"Yvette D",lastName:"Clarke",info:"U.S. House (D) - NY"},
{voteSmartId:44785,firstName:"Domenic",lastName:"Recchia",info:"U.S. House (D) - NY"},
{voteSmartId:45015,firstName:"Mark",lastName:"Assini",info:"U.S. House (R) - NY"},
{voteSmartId:45281,firstName:"Jim",lastName:"Condit",info:"U.S. House (O) - OH"},
{voteSmartId:45333,firstName:"Steve",lastName:"Stivers",info:"U.S. House (R) - OH"},
{voteSmartId:45519,firstName:"Michael R",lastName:"Turner",info:"U.S. House (R) - OH"},
{voteSmartId:45718,firstName:"Jennifer",lastName:"Garrison",info:"U.S. House (D) - OH"},
{voteSmartId:46508,firstName:"James",lastName:"Buchal",info:"U.S. House (R) - OR"},
{voteSmartId:46605,firstName:"Tootie",lastName:"Smith",info:"U.S. House (R) - OR"},
{voteSmartId:49198,firstName:"Ted",lastName:"Poe",info:"U.S. House (R) - TX"},
{voteSmartId:49227,firstName:"Joaquin",lastName:"Castro",info:"U.S. House (D) - TX"},
{voteSmartId:49671,firstName:"Marc",lastName:"Veasey",info:"U.S. House (D) - TX"},
{voteSmartId:49680,firstName:"Al",lastName:"Green",info:"U.S. House (D) - TX"},
{voteSmartId:50544,firstName:"Rob",lastName:"Bishop",info:"U.S. House (R) - UT"},
{voteSmartId:51272,firstName:"Peter",lastName:"Welch",info:"U.S. House (D) - VT"},
{voteSmartId:51346,firstName:"Dave",lastName:"Reichert",info:"U.S. House (R) - WA"},
{voteSmartId:51516,firstName:"Derek",lastName:"Kilmer",info:"U.S. House (D) - WA"},
{voteSmartId:53658,firstName:"John",lastName:"Carney",info:"U.S. House (D) - DE"},
{voteSmartId:53825,firstName:"Kathy",lastName:"Castor",info:"U.S. House (D) - FL"},
{voteSmartId:53922,firstName:"Carl",lastName:"Domino",info:"U.S. House (R) - FL"},
{voteSmartId:55285,firstName:"Hakeem",lastName:"Jeffries",info:"U.S. House (D) - NY"},
{voteSmartId:55440,firstName:"Steve",lastName:"Israel",info:"U.S. House (D) - NY"},
{voteSmartId:55787,firstName:"Jim",lastName:"Langevin",info:"U.S. House (D) - RI"},
{voteSmartId:56231,firstName:"Rick",lastName:"Larsen",info:"U.S. House (D) - WA"},
{voteSmartId:56453,firstName:"Glen",lastName:"Gainer",info:"U.S. House (D) - WV"},
{voteSmartId:56510,firstName:"Eric M",lastName:"Wallace",info:"U.S. House (R) - IL"},
{voteSmartId:56766,firstName:"Brad",lastName:"Ashford",info:"U.S. House (D) - NE"},
{voteSmartId:57124,firstName:"Staci",lastName:"Appel",info:"U.S. House (D) - IA"},
{voteSmartId:57442,firstName:"Tammy",lastName:"Duckworth",info:"U.S. House (D) - IL"},
{voteSmartId:58133,firstName:"Rob",lastName:"Wittman",info:"U.S. House (R) - VA"},
{voteSmartId:58579,firstName:"John A",lastName:"Yarmuth",info:"U.S. House (D) - KY"},
{voteSmartId:58604,firstName:"Janice",lastName:"Kovach",info:"U.S. House (D) - NJ"},
{voteSmartId:58776,firstName:"Eddie",lastName:"Zamora",info:"U.S. House (R) - TX"},
{voteSmartId:59492,firstName:"Max",lastName:"Koch",info:"U.S. House (L) - TX"},
{voteSmartId:59641,firstName:"Suzanne",lastName:"Bonamici",info:"U.S. House (D) - OR"},
{voteSmartId:59849,firstName:"Jared",lastName:"Huffman",info:"U.S. House (D) - CA"},
{voteSmartId:59904,firstName:"Julia",lastName:"Brownley",info:"U.S. House (D) - CA"},
{voteSmartId:60110,firstName:"Tom",lastName:"Houghton",info:"U.S. House (D) - PA"},
{voteSmartId:65085,firstName:"Donna",lastName:"Edwards",info:"U.S. House (D) - MD"},
{voteSmartId:65306,firstName:"Phil",lastName:"Roe",info:"U.S. House (R) - TN"},
{voteSmartId:65443,firstName:"Timothy J",lastName:"Walz",info:"U.S. House (D) - MN"},
{voteSmartId:65891,firstName:"Carol",lastName:"Shea-Porter",info:"U.S. House (D) - NH"},
{voteSmartId:66247,firstName:"Vernon",lastName:"Buchanan",info:"U.S. House (R) - FL"},
{voteSmartId:66575,firstName:"John",lastName:"Sarbanes",info:"U.S. House (D) - MD"},
{voteSmartId:67151,firstName:"Ted",lastName:"Deutch",info:"U.S. House (D) - FL"},
{voteSmartId:68010,firstName:"Al",lastName:"Mcaffrey",info:"U.S. House (D) - OK"},
{voteSmartId:68070,firstName:"Hank",lastName:"Johnson",info:"U.S. House (D) - GA"},
{voteSmartId:68184,firstName:"Alan",lastName:"Grayson",info:"U.S. House (D) - FL"},
{voteSmartId:68394,firstName:"Dan",lastName:"Debicella",info:"U.S. House (R) - CT"},
{voteSmartId:68755,firstName:"Mike",lastName:"Obermueller",info:"U.S. House (D) - MN"},
{voteSmartId:68959,firstName:"Dan",lastName:"Maffei",info:"U.S. House (D) - NY"},
{voteSmartId:68964,firstName:"David",lastName:"Loebsack",info:"U.S. House (D) - IA"},
{voteSmartId:69157,firstName:"Grace",lastName:"Meng",info:"U.S. House (D) - NY"},
{voteSmartId:69477,firstName:"Mark",lastName:"Desaulnier",info:"U.S. House (D) - CA"},
{voteSmartId:70114,firstName:"Pete",lastName:"Aguilar",info:"U.S. House (D) - CA"},
{voteSmartId:70351,firstName:"Scott",lastName:"Peters",info:"U.S. House (D) - CA"},
{voteSmartId:70502,firstName:"Janice",lastName:"Hahn",info:"U.S. House (D) - CA"},
{voteSmartId:71098,firstName:"Steve",lastName:"Knight",info:"U.S. House (R) - CA"},
{voteSmartId:71284,firstName:"Norma",lastName:"Torres",info:"U.S. House (D) - CA"},
{voteSmartId:71604,firstName:"Martha",lastName:"Roby",info:"U.S. House (R) - AL"},
{voteSmartId:71778,firstName:"Patrick Henry",lastName:"Hays",info:"U.S. House (D) - AR"},
{voteSmartId:72764,firstName:"Mark",lastName:"Greenberg",info:"U.S. House (R) - CT"},
{voteSmartId:72826,firstName:"Elizabeth",lastName:"Esty",info:"U.S. House (D) - CT"},
{voteSmartId:74045,firstName:"Jim",lastName:"Sherow",info:"U.S. House (D) - KS"},
{voteSmartId:78533,firstName:"Beto",lastName:"O'Rourke",info:"U.S. House (D) - TX"},
{voteSmartId:78851,firstName:"Brenda",lastName:"Lawrence",info:"U.S. House (D) - MI"},
{voteSmartId:79019,firstName:"Susan",lastName:"Narvaiz",info:"U.S. House (R) - TX"},
{voteSmartId:80427,firstName:"Kat",lastName:"Swift",info:"U.S. House (O) - TX"},
{voteSmartId:83310,firstName:"Mike",lastName:"Quigley",info:"U.S. House (D) - IL"},
{voteSmartId:84917,firstName:"Andre",lastName:"Carson",info:"U.S. House (D) - IN"},
{voteSmartId:89417,firstName:"Niki",lastName:"Tsongas",info:"U.S. House (D) - MA"},
{voteSmartId:90668,firstName:"Donald M Jr",lastName:"Payne",info:"U.S. House (D) - NJ"},
{voteSmartId:91556,firstName:"Martha",lastName:"Robertson",info:"U.S. House (D) - NY"},
{voteSmartId:93593,firstName:"Neil",lastName:"Riser",info:"U.S. House (R) - LA"},
{voteSmartId:95078,firstName:"Gerry",lastName:"Connolly",info:"U.S. House (D) - VA"},
{voteSmartId:102009,firstName:"Ryan",lastName:"Rowley",info:"U.S. House (L) - TX"},
{voteSmartId:102092,firstName:"John",lastName:"Wieder",info:"U.S. House (L) - TX"},
{voteSmartId:102098,firstName:"Ross",lastName:"Leone",info:"U.S. House (L) - TX"},
{voteSmartId:102176,firstName:"Ken",lastName:"Petty",info:"U.S. House (L) - TX"},
{voteSmartId:102404,firstName:"Michelle Lujan",lastName:"Grisham",info:"U.S. House (D) - NM"},
{voteSmartId:102842,firstName:"Ben R",lastName:"Lujan",info:"U.S. House (D) - NM"},
{voteSmartId:102880,firstName:"Catherine",lastName:"Ping",info:"U.S. House (R) - IN"},
{voteSmartId:103294,firstName:"Mariannette",lastName:"Miller-Meeks",info:"U.S. House (R) - IA"},
{voteSmartId:103492,firstName:"Luz",lastName:"Robles",info:"U.S. House (D) - UT"},
{voteSmartId:104422,firstName:"Brian",lastName:"Nestande",info:"U.S. House (R) - CA"},
{voteSmartId:106220,firstName:"Jared",lastName:"Polis",info:"U.S. House (D) - CO"},
{voteSmartId:106393,firstName:"Don",lastName:"Ytterberg",info:"U.S. House (R) - CO"},
{voteSmartId:106744,firstName:"Jim",lastName:"Himes",info:"U.S. House (D) - CT"},
{voteSmartId:107000,firstName:"Kelly",lastName:"Kultala",info:"U.S. House (D) - KS"},
{voteSmartId:107800,firstName:"Tom",lastName:"Rooney",info:"U.S. House (R) - FL"},
{voteSmartId:108811,firstName:"John",lastName:"Fleming",info:"U.S. House (R) - LA"},
{voteSmartId:109074,firstName:"Rob",lastName:"Zerban",info:"U.S. House (D) - WI"},
{voteSmartId:110344,firstName:"Richard",lastName:"Hanna",info:"U.S. House (R) - NY"},
{voteSmartId:110640,firstName:"Marcia L",lastName:"Fudge",info:"U.S. House (D) - OH"},
{voteSmartId:110744,firstName:"William",lastName:"Enyart",info:"U.S. House (D) - IL"},
{voteSmartId:113676,firstName:"Patrice",lastName:"Douglas",info:"U.S. House (R) - OK"},
{voteSmartId:114185,firstName:"Rocky",lastName:"Lara",info:"U.S. House (D) - NM"},
{voteSmartId:114790,firstName:"Jonathan",lastName:"Barfield",info:"U.S. House (D) - NC"},
{voteSmartId:116277,firstName:"Don",lastName:"Norcross",info:"U.S. House (D) - NJ"},
{voteSmartId:116546,firstName:"Susanne",lastName:"Atanus",info:"U.S. House (R) - IL"},
{voteSmartId:116548,firstName:"Bob",lastName:"Dold",info:"U.S. House (R) - IL"},
{voteSmartId:116560,firstName:"Darrel",lastName:"Miller",info:"U.S. House (D) - IL"},
{voteSmartId:116911,firstName:"Will",lastName:"Hurd",info:"U.S. House (R) - TX"},
{voteSmartId:117004,firstName:"David",lastName:"Cozad",info:"U.S. House (D) - TX"},
{voteSmartId:117150,firstName:"Gary",lastName:"Koniz",info:"U.S. House (O) - FL"},
{voteSmartId:117151,firstName:"John E",lastName:"Krause",info:"U.S. House (R) - FL"},
{voteSmartId:117191,firstName:"Ray",lastName:"Netherwood",info:"U.S. House (L) - FL"},
{voteSmartId:117225,firstName:"Nicholas Iii",lastName:"Ruiz",info:"U.S. House (D) - FL"},
{voteSmartId:117272,firstName:"Nick",lastName:"Wukoson",info:"U.S. House (R) - FL"},
{voteSmartId:119120,firstName:"Bruce",lastName:"Westerman",info:"U.S. House (R) - AR"},
{voteSmartId:119208,firstName:"Rick",lastName:"Crawford",info:"U.S. House (R) - AR"},
{voteSmartId:119487,firstName:"Dee",lastName:"Adcock",info:"U.S. House (R) - PA"},
{voteSmartId:120030,firstName:"Ami",lastName:"Bera",info:"U.S. House (D) - CA"},
{voteSmartId:120040,firstName:"John",lastName:"Dennis",info:"U.S. House (R) - CA"},
{voteSmartId:120045,firstName:"Tony",lastName:"Amador",info:"U.S. House (R) - CA"},
{voteSmartId:120264,firstName:"Paul",lastName:"Chabot",info:"U.S. House (R) - CA"},
{voteSmartId:120607,firstName:"Dennis G",lastName:"Lambert",info:"U.S. House (O) - OH"},
{voteSmartId:120897,firstName:"Renee",lastName:"Ellmers",info:"U.S. House (R) - NC"},
{voteSmartId:120909,firstName:"Bruce",lastName:"Poliquin",info:"U.S. House (R) - ME"},
{voteSmartId:121610,firstName:"Mo",lastName:"Brooks",info:"U.S. House (R) - AL"},
{voteSmartId:121621,firstName:"Terri A",lastName:"Sewell",info:"U.S. House (D) - AL"},
{voteSmartId:121872,firstName:"Cresent",lastName:"Hardy",info:"U.S. House (R) - NV"},
{voteSmartId:122251,firstName:"Rob",lastName:"Woodall",info:"U.S. House (R) - GA"},
{voteSmartId:122256,firstName:"Ann Mclane",lastName:"Kuster",info:"U.S. House (D) - NH"},
{voteSmartId:123594,firstName:"Bill",lastName:"Slantz",info:"U.S. House (L) - MO"},
{voteSmartId:123618,firstName:"Wendy",lastName:"Rogers",info:"U.S. House (R) - AZ"},
{voteSmartId:123732,firstName:"Ruben",lastName:"Gallego",info:"U.S. House (D) - AZ"},
{voteSmartId:123939,firstName:"Mark",lastName:"Boler",info:"U.S. House (L) - TX"},
{voteSmartId:124296,firstName:"Michael A",lastName:"Etienne",info:"U.S. House (D) - FL"},
{voteSmartId:124355,firstName:"Joe",lastName:"Garcia",info:"U.S. House (D) - FL"},
{voteSmartId:124933,firstName:"Tom",lastName:"Guild",info:"U.S. House (D) - OK"},
{voteSmartId:125319,firstName:"Ken",lastName:"Buck",info:"U.S. House (R) - CO"},
{voteSmartId:125768,firstName:"Arvin",lastName:"Vohra",info:"U.S. House (L) - MD"},
{voteSmartId:126058,firstName:"Dennis",lastName:"Heck",info:"U.S. House (D) - WA"},
{voteSmartId:134933,firstName:"Jimmy Lee",lastName:"Tillman",info:"U.S. House (R) - IL"},
{voteSmartId:134964,firstName:"Cheri",lastName:"Bustos",info:"U.S. House (D) - IL"},
{voteSmartId:135143,firstName:"John K",lastName:"Delaney",info:"U.S. House (D) - MD"},
{voteSmartId:135649,firstName:"Scott J",lastName:"Ballard",info:"U.S. House (L) - TX"},
{voteSmartId:135977,firstName:"Susan Hall",lastName:"Heitzman",info:"U.S. House (D) - IN"},
{voteSmartId:136062,firstName:"Richard W",lastName:"Allen",info:"U.S. House (R) - GA"},
{voteSmartId:137652,firstName:"Patrick E",lastName:"Murphy",info:"U.S. House (D) - FL"},
{voteSmartId:137691,firstName:"Tawana W",lastName:"Cadien",info:"U.S. House (D) - TX"},
{voteSmartId:137719,firstName:"Filemon",lastName:"Vela",info:"U.S. House (D) - TX"},
{voteSmartId:139705,firstName:"John",lastName:"Betz",info:"U.S. House (L) - TX"},
{voteSmartId:139760,firstName:"Sean Patrick",lastName:"Maloney",info:"U.S. House (D) - NY"},
{voteSmartId:140306,firstName:"David Donald",lastName:"Vogel",info:"U.S. House (D) - GA"},
{voteSmartId:141275,firstName:"Joe Iii",lastName:"Kennedy",info:"U.S. House (D) - MA"},
{voteSmartId:141376,firstName:"Adam Charles",lastName:"Kwasman",info:"U.S. House (R) - AZ"},
{voteSmartId:143205,firstName:"Jaime O",lastName:"Perez",info:"U.S. House (L) - TX"},
{voteSmartId:144457,firstName:"Douglas",lastName:"Enyart",info:"U.S. House (O) - MO"},
{voteSmartId:145981,firstName:"Dale Kenneth",lastName:"Mensing",info:"U.S. House (R) - CA"},
{voteSmartId:145999,firstName:"Corinna",lastName:"Robinson",info:"U.S. House (D) - SD"},
{voteSmartId:146008,firstName:"Robin Leo",lastName:"Chew",info:"U.S. House (R) - CA"},
{voteSmartId:146018,firstName:"Erin Bilbray",lastName:"Kohn",info:"U.S. House (D) - NV"},
{voteSmartId:146062,firstName:"Barbara Hamill",lastName:"Stocker",info:"U.S. House (D) - MO"},
{voteSmartId:146072,firstName:"Michael",lastName:"Frese",info:"U.S. House (R) - NM"},
{voteSmartId:146075,firstName:"Shelley",lastName:"Kais",info:"U.S. House (R) - AZ"},
{voteSmartId:146083,firstName:"Dave",lastName:"Banach",info:"U.S. House (R) - MD"},
{voteSmartId:146104,firstName:"Mark A",lastName:"Gatton",info:"U.S. House (O) - KY"},
{voteSmartId:146112,firstName:"Paul",lastName:"Dietzel",info:"U.S. House (R) - LA"},
{voteSmartId:146130,firstName:"Gloreatha",lastName:"Scurry-Smith",info:"U.S. House (R) - FL"},
{voteSmartId:146133,firstName:"Gabriel",lastName:"Rothblatt",info:"U.S. House (D) - FL"},
{voteSmartId:146152,firstName:"Jay Alan",lastName:"Bonner",info:"U.S. House (R) - FL"},
{voteSmartId:146153,firstName:"Emmanuel G",lastName:"Morel",info:"U.S. House (D) - FL"},
{voteSmartId:146157,firstName:"Lorenzo",lastName:"Palomares-Starbuck",info:"U.S. House (R) - FL"},
{voteSmartId:146157,firstName:"Lorenzo",lastName:"Starbuck",info:"U.S. House (R) - FL"},
{voteSmartId:146200,firstName:"Amos Scott",lastName:"Powers",info:"U.S. House (D) - TN"},
{voteSmartId:146212,firstName:"Lawrence Joseph",lastName:"Kaifesh",info:"U.S. House (R) - IL"},
{voteSmartId:146251,firstName:"Andrew",lastName:"Whallon",info:"U.S. House (R) - CA"},
{voteSmartId:146255,firstName:"Bradley",lastName:"Walker",info:"U.S. House (R) - NC"},
{voteSmartId:146267,firstName:"Jesse T",lastName:"Smith",info:"U.S. House (D) - AL"},
{voteSmartId:146280,firstName:"James Alan",lastName:"Samuelson",info:"U.S. House (I) - AZ"},
{voteSmartId:146300,firstName:"Mark C",lastName:"Alliegro",info:"U.S. House (R) - MA"},
{voteSmartId:147353,firstName:"Michael",lastName:"Minter",info:"U.S. House (D) - TX"},
{voteSmartId:147364,firstName:"Frank",lastName:"Briscoe",info:"U.S. House (D) - TX"},
{voteSmartId:147700,firstName:"Daniel Nelson",lastName:"Cramer",info:"U.S. House (D) - TN"},
{voteSmartId:149728,firstName:"Andrea Leigh",lastName:"Mcgee",info:"U.S. House (R) - FL"},
{voteSmartId:149826,firstName:"Tate",lastName:"Macqueen",info:"U.S. House (D) - NC"},
{voteSmartId:150667,firstName:"David",lastName:"Tibbs",info:"U.S. House (D) - OH"},
{voteSmartId:150716,firstName:"Scott Floyd",lastName:"Brion",info:"U.S. House (D) - PA"},
{voteSmartId:150811,firstName:"David",lastName:"Moylan",info:"U.S. House (R) - PA"},
{voteSmartId:150880,firstName:"Kerith Strano",lastName:"Taylor",info:"U.S. House (D) - PA"},
{voteSmartId:151672,firstName:"Suzanna",lastName:"Marrero-Aguilera",info:"U.S. House (D) - CA"},
{voteSmartId:151681,firstName:"Peter O",lastName:"Anderson",info:"U.S. House (D) - CA"},
{voteSmartId:151838,firstName:"Tue Phan",lastName:"Quang",info:"U.S. House (R) - CA"},
{voteSmartId:151855,firstName:"Suzanne Joyce",lastName:"Savary",info:"U.S. House (D) - CA"},
{voteSmartId:152113,firstName:"Thomas",lastName:"Macarthur",info:"U.S. House (R) - NJ"},
{voteSmartId:152469,firstName:"Paul Colin",lastName:"Clements",info:"U.S. House (D) - MI"},
{voteSmartId:153024,firstName:"Irving Jr",lastName:"Halter",info:"U.S. House (D) - CO"},
{voteSmartId:153203,firstName:"Lenda",lastName:"Sherrell",info:"U.S. House (D) - TN"},
{voteSmartId:153344,firstName:"Jose Luis",lastName:"Fernandez",info:"U.S. House (R) - NY"},
{voteSmartId:153483,firstName:"Doren, Ken",lastName:"Van Doren",info:"U.S. House (R) - WI"},
{voteSmartId:154749,firstName:"Lori Hopkins",lastName:"Cavanagh",info:"U.S. House (R) - CT"},
{voteSmartId:155118,firstName:"Cory",lastName:"Bruner",info:"U.S. House (L) - TX"},
{voteSmartId:155129,firstName:"H J Jr",lastName:"Ridley",info:"U.S. House (O) - TX"},
{voteSmartId:155186,firstName:"Davy",lastName:"Jones",info:"U.S. House (L) - WV"},
{voteSmartId:35,firstName:"Mark",lastName:"Pryor",info:"U.S. Senate (D) - AR"},
{voteSmartId:379,firstName:"Susan M",lastName:"Collins",info:"U.S. Senate (R) - ME"},
{voteSmartId:443,firstName:"Jeff",lastName:"Sessions",info:"U.S. Senate (R) - AL"},
{voteSmartId:558,firstName:"Mike",lastName:"Enzi",info:"U.S. Senate (R) - WY"},
{voteSmartId:2919,firstName:"James E",lastName:"Risch",info:"U.S. Senate (R) - ID"},
{voteSmartId:7455,firstName:"Mike",lastName:"Rounds",info:"U.S. Senate (R) - SD"},
{voteSmartId:11701,firstName:"Shelley Moore",lastName:"Capito",info:"U.S. Senate (R) - WV"},
{voteSmartId:15375,firstName:"John",lastName:"Cornyn",info:"U.S. Senate (R) - TX"},
{voteSmartId:21992,firstName:"Lindsey",lastName:"Graham",info:"U.S. Senate (R) - SC"},
{voteSmartId:26866,firstName:"Pat",lastName:"Roberts",info:"U.S. Senate (R) - KS"},
{voteSmartId:27027,firstName:"James M",lastName:"Inhofe",info:"U.S. Senate (R) - OK"},
{voteSmartId:30004,firstName:"Cory",lastName:"Gardner",info:"U.S. Senate (R) - CO"},
{voteSmartId:38315,firstName:"Terri Lynn",lastName:"Land",info:"U.S. Senate (R) - MI"},
{voteSmartId:53298,firstName:"Mitch",lastName:"Mcconnell",info:"U.S. Senate (R) - KY"},
{voteSmartId:57717,firstName:"Thom",lastName:"Tillis",info:"U.S. Senate (R) - NC"},
{voteSmartId:69494,firstName:"Bill",lastName:"Cassidy",info:"U.S. Senate (R) - LA"},
{voteSmartId:122834,firstName:"Chris",lastName:"Coons",info:"U.S. Senate (D) - DE"},
{voteSmartId:124938,firstName:"James",lastName:"Lankford",info:"U.S. Senate (R) - OK"},
{voteSmartId:128583,firstName:"Joni",lastName:"Ernst",info:"U.S. Senate (R) - IA"},
{voteSmartId:135651,firstName:"Tom",lastName:"Cotton",info:"U.S. Senate (R) - AR"},
{voteSmartId:135720,firstName:"Steven",lastName:"Daines",info:"U.S. Senate (R) - MT"},
{voteSmartId:147792,firstName:"Ed",lastName:"Gillespie",info:"U.S. Senate (R) - VA"},
{voteSmartId:150182,firstName:"Ben",lastName:"Sasse",info:"U.S. Senate (R) - NE"},
{voteSmartId:151332,firstName:"Michelle",lastName:"Nunn",info:"U.S. Senate (D) - GA"},
{voteSmartId:128674,firstName:"Alison",lastName:"Grimes",info:"U.S. Senate (D) - KY"},
{voteSmartId:146068,firstName:"Andy",lastName:"Martin",info:"U.S. Senate (R) - NH"},
{voteSmartId:145148,firstName:"Antonio",lastName:"Sabas",info:"U.S. Senate (I) - NJ"},
{voteSmartId:138424,firstName:"Avery",lastName:"Ayers",info:"U.S. Senate (I) - TX"},
{voteSmartId:146173,firstName:"Brannon",lastName:"Mcmorris",info:"U.S. Senate (L) - LA"},
{voteSmartId:153685,firstName:"Dan",lastName:"Sullivan",info:"U.S. Senate (R) - AK"},
{voteSmartId:146209,firstName:"Danny",lastName:"Page",info:"U.S. Senate (R) - TN"},
{voteSmartId:147882,firstName:"Dave",lastName:"Domina",info:"U.S. Senate (D) - NE"},
{voteSmartId:135595,firstName:"David",lastName:"Alameel",info:"U.S. Senate (D) - TX"},
{voteSmartId:151330,firstName:"David",lastName:"Perdue",info:"U.S. Senate (R) - GA"},
{voteSmartId:155104,firstName:"Emily",lastName:"Sanchez",info:"U.S. Senate (O) - TX"},
{voteSmartId:153187,firstName:"Gordon",lastName:"Ball",info:"U.S. Senate (D) - TN"},
{voteSmartId:152104,firstName:"Jeff",lastName:"Bell",info:"U.S. Senate (R) - NJ"},
{voteSmartId:155048,firstName:"Jim",lastName:"Fulner",info:"U.S. Senate (L) - MI"},
{voteSmartId:146217,firstName:"Matt",lastName:"Silverstein",info:"U.S. Senate (D) - OK"},
{voteSmartId:146024,firstName:"Mike",lastName:"Mcfadden",info:"U.S. Senate (R) - MN"},
{voteSmartId:150683,firstName:"Monica",lastName:"Wehby",info:"U.S. Senate (R) - OR"},
{voteSmartId:147766,firstName:"Nels",lastName:"Mitchell",info:"U.S. Senate (D) - ID"},
{voteSmartId:155103,firstName:"Rebecca",lastName:"Paddock",info:"U.S. Senate (L) - TX"},
{voteSmartId:154650,firstName:"Sharon",lastName:"Hansen",info:"U.S. Senate (L) - IL"},
{voteSmartId:151344,firstName:"Shenna",lastName:"Bellows",info:"U.S. Senate (D) - ME"},
{voteSmartId:397,firstName:"Rick",lastName:"Weiland",info:"U.S. Senate (D) - SD"},
{voteSmartId:535,firstName:"Mark",lastName:"Warner",info:"U.S. Senate (D) - VA"},
{voteSmartId:661,firstName:"Mary L",lastName:"Landrieu",info:"U.S. Senate (D) - LA"},
{voteSmartId:1663,firstName:"Jeanne",lastName:"Shaheen",info:"U.S. Senate (D) - NH"},
{voteSmartId:8660,firstName:"Jim",lastName:"Rubens",info:"U.S. Senate (R) - NH"},
{voteSmartId:12329,firstName:"Mark",lastName:"Udall",info:"U.S. Senate (D) - CO"},
{voteSmartId:15691,firstName:"Lamar",lastName:"Alexander",info:"U.S. Senate (R) - TN"},
{voteSmartId:17852,firstName:"Brian",lastName:"Schatz",info:"U.S. Senate (D) - HI"},
{voteSmartId:21082,firstName:"Kay R",lastName:"Hagan",info:"U.S. Senate (D) - NC"},
{voteSmartId:22658,firstName:"Tom",lastName:"Udall",info:"U.S. Senate (D) - NM"},
{voteSmartId:23644,firstName:"Jeff",lastName:"Merkley",info:"U.S. Senate (D) - OR"},
{voteSmartId:24688,firstName:"Eugene",lastName:"Lavergne",info:"U.S. Senate (O) - NJ"},
{voteSmartId:26847,firstName:"Dick",lastName:"Durbin",info:"U.S. Senate (D) - IL"},
{voteSmartId:26900,firstName:"Ed",lastName:"Markey",info:"U.S. Senate (D) - MA"},
{voteSmartId:27060,firstName:"Jack",lastName:"Reed",info:"U.S. Senate (D) - RI"},
{voteSmartId:33522,firstName:"James D",lastName:"Oberweis",info:"U.S. Senate (R) - IL"},
{voteSmartId:53312,firstName:"Thad",lastName:"Cochran",info:"U.S. Senate (R) - MS"},
{voteSmartId:53346,firstName:"Larry",lastName:"Pressler",info:"U.S. Senate (I) - SD"},
{voteSmartId:57382,firstName:"Bruce",lastName:"Braley",info:"U.S. Senate (D) - IA"},
{voteSmartId:76151,firstName:"Cory",lastName:"Booker",info:"U.S. Senate (D) - NJ"},
{voteSmartId:79426,firstName:"Mark",lastName:"Begich",info:"U.S. Senate (D) - AK"},
{voteSmartId:96848,firstName:"Joyce",lastName:"Dickerson",info:"U.S. Senate (D) - SC"},
{voteSmartId:108924,firstName:"Al",lastName:"Franken",info:"U.S. Senate (D) - MN"},
{voteSmartId:110922,firstName:"Natalie",lastName:"Tennant",info:"U.S. Senate (D) - WV"},
{voteSmartId:117554,firstName:"Ed",lastName:"Marksberry",info:"U.S. Senate (D) - KY"},
{voteSmartId:121634,firstName:"Allen",lastName:"Weh",info:"U.S. Senate (R) - NM"},
{voteSmartId:124898,firstName:"Brian",lastName:"Herr",info:"U.S. Senate (R) - MA"},
{voteSmartId:146206,firstName:"Chad",lastName:"Taylor",info:"U.S. Senate (D) - KS"},
{voteSmartId:152224,firstName:"Joan Elizabeth",lastName:"Farr",info:"U.S. Senate (I) - OK"},
{voteSmartId:155013,firstName:"Stephen H",lastName:"Shogan",info:"U.S. Senate (I) - CO"},
{voteSmartId:155194,firstName:"Jim",lastName:"Jenkins",info:"U.S. Senate (I) - NE"},
{voteSmartId:5121,firstName:"Eric",lastName:"Cantor",info:"U.S. House (R) - VA"},
{voteSmartId:8751,firstName:"Mike",lastName:"Rogers",info:"U.S. House (R) - MI"},
{voteSmartId:22175,firstName:"Tom",lastName:"Latham",info:"U.S. House (R) - IA"},
{voteSmartId:22318,firstName:"Doc",lastName:"Hastings",info:"U.S. House (R) - WA"},
{voteSmartId:26911,firstName:"Dave",lastName:"Camp",info:"U.S. House (R) - MI"},
{voteSmartId:32008,firstName:"Ed",lastName:"Lindsey",info:"U.S. House (R) - GA"},
{voteSmartId:50722,firstName:"Jim",lastName:"Matheson",info:"U.S. House (D) - UT"},
{voteSmartId:73695,firstName:"Matt",lastName:"Schultz",info:"U.S. House (R) - IA"},
{voteSmartId:121117,firstName:"Jon",lastName:"Runyan",info:"U.S. House (R) - NJ"},
{voteSmartId:137658,firstName:"Trey",lastName:"Radel",info:"U.S. House (R) - FL"},
{voteSmartId:145940,firstName:"Chad",lastName:"Mathis",info:"U.S. House (R) - AL"},
{voteSmartId:145984,firstName:"Igor A",lastName:"Birman",info:"U.S. House (R) - CA"},
{voteSmartId:146159,firstName:"Jeff",lastName:"Duncan",info:"U.S. House (R) - SC"},
{voteSmartId:146189,firstName:"Bryan",lastName:"Smith",info:"U.S. House (R) - ID"},
{voteSmartId:146222,firstName:"Bert",lastName:"Miller",info:"U.S. House (R) - IL"},
{voteSmartId:146234,firstName:"Taylor",lastName:"Griffin",info:"U.S. House (R) - NC"},
{voteSmartId:398,firstName:"John",lastName:"Thune",info:"U.S. Senate (R) - SD"},
{voteSmartId:4615,firstName:"David",lastName:"Vitter",info:"U.S. Senate (R) - LA"},
{voteSmartId:24096,firstName:"Pat",lastName:"Toomey",info:"U.S. Senate (R) - PA"},
{voteSmartId:26816,firstName:"Jack",lastName:"Kingston",info:"U.S. Senate (R) - GA"},
{voteSmartId:27008,firstName:"Rob",lastName:"Portman",info:"U.S. Senate (R) - OH"},
{voteSmartId:28128,firstName:"Jeff",lastName:"Flake",info:"U.S. Senate (R) - AZ"},
{voteSmartId:33502,firstName:"Mark",lastName:"Kirk",info:"U.S. Senate (R) - IL"},
{voteSmartId:42352,firstName:"Kelly",lastName:"Ayotte",info:"U.S. Senate (R) - NH"},
{voteSmartId:65366,firstName:"T W",lastName:"Shannon",info:"U.S. Senate (R) - OK"},
{voteSmartId:69553,firstName:"Karen",lastName:"Handel",info:"U.S. Senate (R) - GA"},
{voteSmartId:69837,firstName:"Chris",lastName:"Mcdaniel",info:"U.S. Senate (R) - MS"},
{voteSmartId:70001,firstName:"Paul",lastName:"Broun",info:"U.S. Senate (R) - GA"},
{voteSmartId:117285,firstName:"Rand",lastName:"Paul",info:"U.S. Senate (R) - KY"},
{voteSmartId:117344,firstName:"Jason",lastName:"Conger",info:"U.S. Senate (R) - OR"},
{voteSmartId:123210,firstName:"Mead",lastName:"Treadwell",info:"U.S. Senate (R) - AK"},
{voteSmartId:125362,firstName:"Owen",lastName:"Hill",info:"U.S. Senate (R) - CO"},
{voteSmartId:126217,firstName:"Ron",lastName:"Johnson",info:"U.S. Senate (R) - WI"},
{voteSmartId:135705,firstName:"Ted",lastName:"Cruz",info:"U.S. Senate (R) - TX"},
{voteSmartId:146094,firstName:"Matt",lastName:"Bevin",info:"U.S. Senate (R) - KY"},
{voteSmartId:146183,firstName:"Mark",lastName:"Jacobs",info:"U.S. Senate (R) - IA"},
{voteSmartId:145932,firstName:"Liz",lastName:"Cheney",info:"Not Available"},
{voteSmartId:146195,firstName:"Luke",lastName:"Messer",info:"Not Available"},
{voteSmartId:155325,firstName:"Nelson F",lastName:"Rimensnyder",info:"Not Available"},
{voteSmartId:542,firstName:"Jerry",lastName:"Moran",info:"Not Available"},
{voteSmartId:77541,firstName:"Mike",lastName:"Sullivan",info:"Not Available"},
{voteSmartId:126258,firstName:"Bill",lastName:"Johnson",info:"Not Available"},
{voteSmartId:129757,firstName:"Bob",lastName:"Johnson",info:"Not Available"},
{voteSmartId:130802,firstName:"Andy",lastName:"Harris",info:"Not Available"},
{voteSmartId:132452,firstName:"Mike",lastName:"Lee",info:"Not Available"},
{voteSmartId:133002,firstName:"Richard",lastName:"Hudson",info:"Not Available"},
{voteSmartId:136858,firstName:"Jason",lastName:"Smith",info:"Not Available"},
{voteSmartId:142486,firstName:"Dan",lastName:"Sullivan",info:"Not Available"},
{voteSmartId:143111,firstName:"Kevin",lastName:"Brady",info:"Not Available"},
{voteSmartId:144464,firstName:"Gabriel",lastName:"Gomez",info:"Not Available"},
{voteSmartId:144588,firstName:"John",lastName:"Campbell",info:"Not Available"},
{voteSmartId:144975,firstName:"Quin",lastName:"Hillyer",info:"Not Available"},
{voteSmartId:147442,firstName:"Kevin",lastName:"Mccarthy",info:"Not Available"},
{voteSmartId:148199,firstName:"Tim",lastName:"Scott",info:"Not Available"}
]

});